/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "nautilus-view-component.h"

void
_ORBIT_skel_Nautilus_View_load_location(POA_Nautilus_View * _ORBIT_servant,
					GIOPRecvBuffer * _ORBIT_recv_buffer,
					CORBA_Environment * ev,
					void (*_impl_load_location)
					(PortableServer_Servant _servant,
					 const Nautilus_URI location,
					 CORBA_Environment * ev))
{
   Nautilus_URI location;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_load_location(_ORBIT_servant, location, ev);
}

void
_ORBIT_skel_Nautilus_View_stop_loading(POA_Nautilus_View * _ORBIT_servant,
				       GIOPRecvBuffer * _ORBIT_recv_buffer,
				       CORBA_Environment * ev,
				       void (*_impl_stop_loading)
				       (PortableServer_Servant _servant,
					CORBA_Environment * ev))
{
   _impl_stop_loading(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_View_selection_changed(POA_Nautilus_View *
					    _ORBIT_servant,
					    GIOPRecvBuffer *
					    _ORBIT_recv_buffer,
					    CORBA_Environment * ev,
					    void (*_impl_selection_changed)
					    (PortableServer_Servant _servant,
					     const Nautilus_URIList *
					     selection,
					     CORBA_Environment * ev))
{
   Nautilus_URIList selection = { 0, 0, NULL, CORBA_FALSE };

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_3;
      register CORBA_unsigned_long _ORBIT_tmpvar_4;
      CORBA_unsigned_long _ORBIT_tmpvar_5;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (selection._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 selection._buffer =
	    alloca(sizeof(selection._buffer[_ORBIT_tmpvar_3]) *
		   selection._length);
	 selection._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_3 = 0; _ORBIT_tmpvar_3 < selection._length;
	      _ORBIT_tmpvar_3++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_5))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    selection._buffer[_ORBIT_tmpvar_3] = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(selection._buffer[_ORBIT_tmpvar_3][_ORBIT_tmpvar_4]) *
	       _ORBIT_tmpvar_5;
	 }

      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 selection._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 selection._buffer =
	    alloca(sizeof(selection._buffer[_ORBIT_tmpvar_3]) *
		   selection._length);
	 selection._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_3 = 0; _ORBIT_tmpvar_3 < selection._length;
	      _ORBIT_tmpvar_3++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_5 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    selection._buffer[_ORBIT_tmpvar_3] = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(selection._buffer[_ORBIT_tmpvar_3][_ORBIT_tmpvar_4]) *
	       _ORBIT_tmpvar_5;
	 }

      }
   }
   _impl_selection_changed(_ORBIT_servant, &(selection), ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_open_location(POA_Nautilus_ViewFrame *
					     _ORBIT_servant,
					     GIOPRecvBuffer *
					     _ORBIT_recv_buffer,
					     CORBA_Environment * ev,
					     void (*_impl_open_location)
					     (PortableServer_Servant _servant,
					      const Nautilus_URI location,
					      CORBA_Environment * ev))
{
   Nautilus_URI location;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_open_location(_ORBIT_servant, location, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_open_location_in_new_window
   (POA_Nautilus_ViewFrame * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    void (*_impl_open_location_in_new_window) (PortableServer_Servant
					       _servant,
					       const Nautilus_URI location,
					       CORBA_Environment * ev))
{
   Nautilus_URI location;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_open_location_in_new_window(_ORBIT_servant, location, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_location_change(POA_Nautilus_ViewFrame *
						      _ORBIT_servant,
						      GIOPRecvBuffer *
						      _ORBIT_recv_buffer,
						      CORBA_Environment * ev,
						      void
						      (*_impl_report_location_change)
						      (PortableServer_Servant
						       _servant,
						       const Nautilus_URI
						       location,
						       CORBA_Environment *
						       ev))
{
   Nautilus_URI location;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 location = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(location[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_report_location_change(_ORBIT_servant, location, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_selection_change(POA_Nautilus_ViewFrame
						       * _ORBIT_servant,
						       GIOPRecvBuffer *
						       _ORBIT_recv_buffer,
						       CORBA_Environment * ev,
						       void
						       (*_impl_report_selection_change)
						       (PortableServer_Servant
							_servant,
							const Nautilus_URIList
							* selection,
							CORBA_Environment *
							ev))
{
   Nautilus_URIList selection = { 0, 0, NULL, CORBA_FALSE };

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_3;
      register CORBA_unsigned_long _ORBIT_tmpvar_4;
      CORBA_unsigned_long _ORBIT_tmpvar_5;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (selection._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 selection._buffer =
	    alloca(sizeof(selection._buffer[_ORBIT_tmpvar_3]) *
		   selection._length);
	 selection._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_3 = 0; _ORBIT_tmpvar_3 < selection._length;
	      _ORBIT_tmpvar_3++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_5))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    selection._buffer[_ORBIT_tmpvar_3] = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(selection._buffer[_ORBIT_tmpvar_3][_ORBIT_tmpvar_4]) *
	       _ORBIT_tmpvar_5;
	 }

      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 selection._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 selection._buffer =
	    alloca(sizeof(selection._buffer[_ORBIT_tmpvar_3]) *
		   selection._length);
	 selection._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_3 = 0; _ORBIT_tmpvar_3 < selection._length;
	      _ORBIT_tmpvar_3++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_5 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    selection._buffer[_ORBIT_tmpvar_3] = (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(selection._buffer[_ORBIT_tmpvar_3][_ORBIT_tmpvar_4]) *
	       _ORBIT_tmpvar_5;
	 }

      }
   }
   _impl_report_selection_change(_ORBIT_servant, &(selection), ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_status(POA_Nautilus_ViewFrame *
					     _ORBIT_servant,
					     GIOPRecvBuffer *
					     _ORBIT_recv_buffer,
					     CORBA_Environment * ev,
					     void (*_impl_report_status)
					     (PortableServer_Servant _servant,
					      const CORBA_char * status,
					      CORBA_Environment * ev))
{
   CORBA_char *status;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 status = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(status[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 status = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(status[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_report_status(_ORBIT_servant, status, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_load_underway(POA_Nautilus_ViewFrame *
						    _ORBIT_servant,
						    GIOPRecvBuffer *
						    _ORBIT_recv_buffer,
						    CORBA_Environment * ev,
						    void
						    (*_impl_report_load_underway)
						    (PortableServer_Servant
						     _servant,
						     CORBA_Environment * ev))
{
   _impl_report_load_underway(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_load_progress(POA_Nautilus_ViewFrame *
						    _ORBIT_servant,
						    GIOPRecvBuffer *
						    _ORBIT_recv_buffer,
						    CORBA_Environment * ev,
						    void
						    (*_impl_report_load_progress)
						    (PortableServer_Servant
						     _servant,
						     const CORBA_double
						     fraction_done,
						     CORBA_Environment * ev))
{
   CORBA_double fraction_done;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 8);
	 iiop_byteswap((guchar *) & (fraction_done), _ORBIT_curptr, 8);
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 8);
	 fraction_done = *((CORBA_double *) _ORBIT_curptr);
      }
   }
   _impl_report_load_progress(_ORBIT_servant, fraction_done, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_load_complete(POA_Nautilus_ViewFrame *
						    _ORBIT_servant,
						    GIOPRecvBuffer *
						    _ORBIT_recv_buffer,
						    CORBA_Environment * ev,
						    void
						    (*_impl_report_load_complete)
						    (PortableServer_Servant
						     _servant,
						     CORBA_Environment * ev))
{
   _impl_report_load_complete(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_report_load_failed(POA_Nautilus_ViewFrame *
						  _ORBIT_servant,
						  GIOPRecvBuffer *
						  _ORBIT_recv_buffer,
						  CORBA_Environment * ev,
						  void
						  (*_impl_report_load_failed)
						  (PortableServer_Servant
						   _servant,
						   CORBA_Environment * ev))
{
   _impl_report_load_failed(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_ViewFrame_set_title(POA_Nautilus_ViewFrame *
					 _ORBIT_servant,
					 GIOPRecvBuffer * _ORBIT_recv_buffer,
					 CORBA_Environment * ev,
					 void (*_impl_set_title)
					 (PortableServer_Servant _servant,
					  const CORBA_char * new_title,
					  CORBA_Environment * ev))
{
   CORBA_char *new_title;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 new_title = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(new_title[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 new_title = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(new_title[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_set_title(_ORBIT_servant, new_title, ev);
}

void
_ORBIT_skel_Nautilus_Zoomable__get_zoom_level(POA_Nautilus_Zoomable *
					      _ORBIT_servant,
					      GIOPRecvBuffer *
					      _ORBIT_recv_buffer,
					      CORBA_Environment * ev,
					      CORBA_double
					      (*_impl__get_zoom_level)
					      (PortableServer_Servant
					       _servant,
					       CORBA_Environment * ev))
{
   CORBA_double _ORBIT_retval;

   _ORBIT_retval = _impl__get_zoom_level(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 8);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Zoomable__set_zoom_level(POA_Nautilus_Zoomable *
					      _ORBIT_servant,
					      GIOPRecvBuffer *
					      _ORBIT_recv_buffer,
					      CORBA_Environment * ev,
					      void (*_impl__set_zoom_level)
					      (PortableServer_Servant
					       _servant,
					       const CORBA_double value,
					       CORBA_Environment * ev))
{
   CORBA_double value;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 8);
	 iiop_byteswap((guchar *) & (value), _ORBIT_curptr, 8);
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 8);
	 value = *((CORBA_double *) _ORBIT_curptr);
      }
   }
   _impl__set_zoom_level(_ORBIT_servant, value, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Zoomable__get_min_zoom_level(POA_Nautilus_Zoomable *
						  _ORBIT_servant,
						  GIOPRecvBuffer *
						  _ORBIT_recv_buffer,
						  CORBA_Environment * ev,
						  CORBA_double
						  (*_impl__get_min_zoom_level)
						  (PortableServer_Servant
						   _servant,
						   CORBA_Environment * ev))
{
   CORBA_double _ORBIT_retval;

   _ORBIT_retval = _impl__get_min_zoom_level(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 8);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Zoomable__get_max_zoom_level(POA_Nautilus_Zoomable *
						  _ORBIT_servant,
						  GIOPRecvBuffer *
						  _ORBIT_recv_buffer,
						  CORBA_Environment * ev,
						  CORBA_double
						  (*_impl__get_max_zoom_level)
						  (PortableServer_Servant
						   _servant,
						   CORBA_Environment * ev))
{
   CORBA_double _ORBIT_retval;

   _ORBIT_retval = _impl__get_max_zoom_level(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 8);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Zoomable__get_is_continuous(POA_Nautilus_Zoomable *
						 _ORBIT_servant,
						 GIOPRecvBuffer *
						 _ORBIT_recv_buffer,
						 CORBA_Environment * ev,
						 CORBA_boolean
						 (*_impl__get_is_continuous)
						 (PortableServer_Servant
						  _servant,
						  CORBA_Environment * ev))
{
   CORBA_boolean _ORBIT_retval;

   _ORBIT_retval = _impl__get_is_continuous(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Nautilus_Zoomable__get_preferred_zoom_levels(POA_Nautilus_Zoomable
							 * _ORBIT_servant,
							 GIOPRecvBuffer *
							 _ORBIT_recv_buffer,
							 CORBA_Environment *
							 ev,
							 Nautilus_ZoomLevelList
							 *
							 (*_impl__get_preferred_zoom_levels)
							 (PortableServer_Servant
							  _servant,
							  CORBA_Environment *
							  ev))
{
   Nautilus_ZoomLevelList *_ORBIT_retval;

   _ORBIT_retval = _impl__get_preferred_zoom_levels(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;

	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof((*_ORBIT_retval)._length));
	       memcpy(_ORBIT_t, &((*_ORBIT_retval)._length),
		      sizeof((*_ORBIT_retval)._length));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof((*_ORBIT_retval).
						     _length));
	    }
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 8);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t =
		  alloca(sizeof((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0]) *
			 (*_ORBIT_retval)._length);
	       memcpy(_ORBIT_t, ((*_ORBIT_retval)._buffer),
		      sizeof((*_ORBIT_retval)._buffer[_ORBIT_tmpvar_0]) *
		      (*_ORBIT_retval)._length);
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof((*_ORBIT_retval).
						     _buffer[_ORBIT_tmpvar_0])
					      * (*_ORBIT_retval)._length);
	    }
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
void
_ORBIT_skel_Nautilus_Zoomable_zoom_in(POA_Nautilus_Zoomable * _ORBIT_servant,
				      GIOPRecvBuffer * _ORBIT_recv_buffer,
				      CORBA_Environment * ev,
				      void (*_impl_zoom_in)
				      (PortableServer_Servant _servant,
				       CORBA_Environment * ev))
{
   _impl_zoom_in(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_Zoomable_zoom_out(POA_Nautilus_Zoomable * _ORBIT_servant,
				       GIOPRecvBuffer * _ORBIT_recv_buffer,
				       CORBA_Environment * ev,
				       void (*_impl_zoom_out)
				       (PortableServer_Servant _servant,
					CORBA_Environment * ev))
{
   _impl_zoom_out(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_Zoomable_zoom_to_fit(POA_Nautilus_Zoomable *
					  _ORBIT_servant,
					  GIOPRecvBuffer * _ORBIT_recv_buffer,
					  CORBA_Environment * ev,
					  void (*_impl_zoom_to_fit)
					  (PortableServer_Servant _servant,
					   CORBA_Environment * ev))
{
   _impl_zoom_to_fit(_ORBIT_servant, ev);
}

void
_ORBIT_skel_Nautilus_ZoomableFrame_report_zoom_level_changed
   (POA_Nautilus_ZoomableFrame * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    void (*_impl_report_zoom_level_changed) (PortableServer_Servant _servant,
					     const CORBA_double zoom_level,
					     CORBA_Environment * ev))
{
   CORBA_double zoom_level;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 8);
	 iiop_byteswap((guchar *) & (zoom_level), _ORBIT_curptr, 8);
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 8);
	 zoom_level = *((CORBA_double *) _ORBIT_curptr);
      }
   }
   _impl_report_zoom_level_changed(_ORBIT_servant, zoom_level, ev);
}

void
_ORBIT_skel_Nautilus_HistoryFrame_get_history_list(POA_Nautilus_HistoryFrame *
						   _ORBIT_servant,
						   GIOPRecvBuffer *
						   _ORBIT_recv_buffer,
						   CORBA_Environment * ev,
						   Nautilus_History *
						   (*_impl_get_history_list)
						   (PortableServer_Servant
						    _servant,
						    CORBA_Environment * ev))
{
   Nautilus_History *_ORBIT_retval;

   _ORBIT_retval = _impl_get_history_list(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    register CORBA_unsigned_long _ORBIT_tmpvar_0;
	    register CORBA_unsigned_long _ORBIT_tmpvar_1;
	    CORBA_unsigned_long _ORBIT_tmpvar_2;
	    register CORBA_unsigned_long _ORBIT_tmpvar_3;
	    CORBA_unsigned_long _ORBIT_tmpvar_4;

	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof((*_ORBIT_retval).list._length));
	       memcpy(_ORBIT_t, &((*_ORBIT_retval).list._length),
		      sizeof((*_ORBIT_retval).list._length));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof((*_ORBIT_retval).list.
						     _length));
	    }
	    for (_ORBIT_tmpvar_0 = 0;
		 _ORBIT_tmpvar_0 < (*_ORBIT_retval).list._length;
		 _ORBIT_tmpvar_0++) {
	       _ORBIT_tmpvar_2 =
		  strlen((*_ORBIT_retval).list._buffer[_ORBIT_tmpvar_0].
			 title) + 1;
	       giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
						(_ORBIT_send_buffer), 4);
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_2));
		  memcpy(_ORBIT_t, &(_ORBIT_tmpvar_2),
			 sizeof(_ORBIT_tmpvar_2));
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof(_ORBIT_tmpvar_2));
	       }
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t =
		     alloca(sizeof
			    ((*_ORBIT_retval).list._buffer[_ORBIT_tmpvar_0].
			     title[_ORBIT_tmpvar_1]) * _ORBIT_tmpvar_2);
		  memcpy(_ORBIT_t,
			 ((*_ORBIT_retval).list._buffer[_ORBIT_tmpvar_0].
			  title),
			 sizeof((*_ORBIT_retval).list.
				_buffer[_ORBIT_tmpvar_0].
				title[_ORBIT_tmpvar_1]) * _ORBIT_tmpvar_2);
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof((*_ORBIT_retval).list.
							_buffer
							[_ORBIT_tmpvar_0].
							title
							[_ORBIT_tmpvar_1]) *
						 _ORBIT_tmpvar_2);
	       }
	       _ORBIT_tmpvar_4 =
		  strlen((*_ORBIT_retval).list._buffer[_ORBIT_tmpvar_0].
			 location) + 1;
	       giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
						(_ORBIT_send_buffer), 4);
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_4));
		  memcpy(_ORBIT_t, &(_ORBIT_tmpvar_4),
			 sizeof(_ORBIT_tmpvar_4));
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof(_ORBIT_tmpvar_4));
	       }
	       {
		  guchar *_ORBIT_t;

		  _ORBIT_t =
		     alloca(sizeof
			    ((*_ORBIT_retval).list._buffer[_ORBIT_tmpvar_0].
			     location[_ORBIT_tmpvar_3]) * _ORBIT_tmpvar_4);
		  memcpy(_ORBIT_t,
			 ((*_ORBIT_retval).list._buffer[_ORBIT_tmpvar_0].
			  location),
			 sizeof((*_ORBIT_retval).list.
				_buffer[_ORBIT_tmpvar_0].
				location[_ORBIT_tmpvar_3]) * _ORBIT_tmpvar_4);
		  giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
						 (_ORBIT_send_buffer),
						 (_ORBIT_t),
						 sizeof((*_ORBIT_retval).list.
							_buffer
							[_ORBIT_tmpvar_0].
							location
							[_ORBIT_tmpvar_3]) *
						 _ORBIT_tmpvar_4);
	       }
	    }

	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer),
					   &((*_ORBIT_retval).position),
					   sizeof((*_ORBIT_retval).position));
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
      if (ev->_major == CORBA_NO_EXCEPTION)
	 CORBA_free(_ORBIT_retval);
   }
}
static ORBitSkeleton
get_skel_Nautilus_View(POA_Nautilus_View * servant,
		       GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'l':
	if (strcmp((opname + 1), "oad_location"))
	   break;
	*impl = (gpointer) servant->vepv->Nautilus_View_epv->load_location;
	return (ORBitSkeleton) _ORBIT_skel_Nautilus_View_load_location;
	break;
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 's':
	switch (opname[1]) {
	  case 'e':
	     if (strcmp((opname + 2), "lection_changed"))
		break;
	     *impl =
		(gpointer) servant->vepv->Nautilus_View_epv->
		selection_changed;
	     return (ORBitSkeleton)
		_ORBIT_skel_Nautilus_View_selection_changed;
	     break;
	  case 't':
	     if (strcmp((opname + 2), "op_loading"))
		break;
	     *impl =
		(gpointer) servant->vepv->Nautilus_View_epv->stop_loading;
	     return (ORBitSkeleton) _ORBIT_skel_Nautilus_View_stop_loading;
	     break;
	  default:
	     break;
	}
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_View(CORBA_Object obj, POA_Nautilus_View * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_View__classid] = servant->vepv->Nautilus_View_epv;
}

void
POA_Nautilus_View__init(PortableServer_Servant servant,
			CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_View, "IDL:Nautilus/View:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_View };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_View__classid)
      Nautilus_View__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_View__fini(PortableServer_Servant servant,
			CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSkeleton
get_skel_Nautilus_ViewFrame(POA_Nautilus_ViewFrame * servant,
			    GIOPRecvBuffer * _ORBIT_recv_buffer,
			    gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'o':
	switch (opname[1]) {
	  case 'p':
	     switch (opname[2]) {
	       case 'e':
		  switch (opname[3]) {
		    case 'n':
		       switch (opname[4]) {
			 case '_':
			    switch (opname[5]) {
			      case 'l':
				 switch (opname[6]) {
				   case 'o':
				      switch (opname[7]) {
					case 'c':
					   switch (opname[8]) {
					     case 'a':
						switch (opname[9]) {
						  case 't':
						     switch (opname[10]) {
						       case 'i':
							  switch (opname[11]) {
							    case 'o':
							       switch (opname
								       [12]) {
								 case 'n':
								    switch
								       (opname
									[13])
								      {
									 case
								      '\0':
									 *impl
									    =
									    (gpointer)
									    servant->
									    vepv->
									    Nautilus_ViewFrame_epv->
									    open_location;
									 return
									    (ORBitSkeleton)
									    _ORBIT_skel_Nautilus_ViewFrame_open_location;
									 break;
									 case
								      '_':
									 if
									    (strcmp
									     (
									      (opname
									       +
									       14),
									      "in_new_window"))
									       break;
									 *impl
									    =
									    (gpointer)
									    servant->
									    vepv->
									    Nautilus_ViewFrame_epv->
									    open_location_in_new_window;
									 return
									    (ORBitSkeleton)
									    _ORBIT_skel_Nautilus_ViewFrame_open_location_in_new_window;
									 break;
								      default:
									 break;
								    }
								    break;
								 default:
								    break;
							       }
							       break;
							    default:
							       break;
							  }
							  break;
						       default:
							  break;
						     }
						     break;
						  default:
						     break;
						}
						break;
					     default:
						break;
					   }
					   break;
					default:
					   break;
				      }
				      break;
				   default:
				      break;
				 }
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 'f':
		  if (strcmp((opname + 3), ""))
		     break;
		  *impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
		  return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
		  break;
	       case 'p':
		  switch (opname[3]) {
		    case 'o':
		       switch (opname[4]) {
			 case 'r':
			    switch (opname[5]) {
			      case 't':
				 switch (opname[6]) {
				   case '_':
				      switch (opname[7]) {
					case 'l':
					   switch (opname[8]) {
					     case 'o':
						switch (opname[9]) {
						  case 'a':
						     switch (opname[10]) {
						       case 'd':
							  switch (opname[11]) {
							    case '_':
							       switch (opname
								       [12]) {
								 case 'c':
								    if (strcmp
									(
									 (opname
									  +
									  13),
									 "omplete"))
									  break;
								    *impl =
								       (gpointer)
								       servant->
								       vepv->
								       Nautilus_ViewFrame_epv->
								       report_load_complete;
								    return
								       (ORBitSkeleton)
								       _ORBIT_skel_Nautilus_ViewFrame_report_load_complete;
								    break;
								 case 'f':
								    if (strcmp
									(
									 (opname
									  +
									  13),
									 "ailed"))
									  break;
								    *impl =
								       (gpointer)
								       servant->
								       vepv->
								       Nautilus_ViewFrame_epv->
								       report_load_failed;
								    return
								       (ORBitSkeleton)
								       _ORBIT_skel_Nautilus_ViewFrame_report_load_failed;
								    break;
								 case 'p':
								    if (strcmp
									(
									 (opname
									  +
									  13),
									 "rogress"))
									  break;
								    *impl =
								       (gpointer)
								       servant->
								       vepv->
								       Nautilus_ViewFrame_epv->
								       report_load_progress;
								    return
								       (ORBitSkeleton)
								       _ORBIT_skel_Nautilus_ViewFrame_report_load_progress;
								    break;
								 case 'u':
								    if (strcmp
									(
									 (opname
									  +
									  13),
									 "nderway"))
									  break;
								    *impl =
								       (gpointer)
								       servant->
								       vepv->
								       Nautilus_ViewFrame_epv->
								       report_load_underway;
								    return
								       (ORBitSkeleton)
								       _ORBIT_skel_Nautilus_ViewFrame_report_load_underway;
								    break;
								 default:
								    break;
							       }
							       break;
							    default:
							       break;
							  }
							  break;
						       default:
							  break;
						     }
						     break;
						  case 'c':
						     if (strcmp
							 ((opname + 10),
							  "ation_change"))
							   break;
						     *impl =
							(gpointer) servant->
							vepv->
							Nautilus_ViewFrame_epv->
							report_location_change;
						     return (ORBitSkeleton)
							_ORBIT_skel_Nautilus_ViewFrame_report_location_change;
						     break;
						  default:
						     break;
						}
						break;
					     default:
						break;
					   }
					   break;
					case 's':
					   switch (opname[8]) {
					     case 'e':
						if (strcmp
						    ((opname + 9),
						     "lection_change")) break;
						*impl =
						   (gpointer) servant->vepv->
						   Nautilus_ViewFrame_epv->
						   report_selection_change;
						return (ORBitSkeleton)
						   _ORBIT_skel_Nautilus_ViewFrame_report_selection_change;
						break;
					     case 't':
						if (strcmp
						    ((opname + 9), "atus"))
						   break;
						*impl =
						   (gpointer) servant->vepv->
						   Nautilus_ViewFrame_epv->
						   report_status;
						return (ORBitSkeleton)
						   _ORBIT_skel_Nautilus_ViewFrame_report_status;
						break;
					     default:
						break;
					   }
					   break;
					default:
					   break;
				      }
				      break;
				   default:
				      break;
				 }
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 's':
	if (strcmp((opname + 1), "et_title"))
	   break;
	*impl = (gpointer) servant->vepv->Nautilus_ViewFrame_epv->set_title;
	return (ORBitSkeleton) _ORBIT_skel_Nautilus_ViewFrame_set_title;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_ViewFrame(CORBA_Object obj,
				     POA_Nautilus_ViewFrame * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_ViewFrame__classid] =
      servant->vepv->Nautilus_ViewFrame_epv;
}

void
POA_Nautilus_ViewFrame__init(PortableServer_Servant servant,
			     CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_ViewFrame,
	 "IDL:Nautilus/ViewFrame:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_ViewFrame };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_ViewFrame__classid)
      Nautilus_ViewFrame__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_ViewFrame__fini(PortableServer_Servant servant,
			     CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSkeleton
get_skel_Nautilus_Zoomable(POA_Nautilus_Zoomable * servant,
			   GIOPRecvBuffer * _ORBIT_recv_buffer,
			   gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case '_':
	switch (opname[1]) {
	  case 'g':
	     switch (opname[2]) {
	       case 'e':
		  switch (opname[3]) {
		    case 't':
		       switch (opname[4]) {
			 case '_':
			    switch (opname[5]) {
			      case 'i':
				 if (strcmp((opname + 6), "s_continuous"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Zoomable_epv->_get_is_continuous;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Zoomable__get_is_continuous;
				 break;
			      case 'm':
				 switch (opname[6]) {
				   case 'a':
				      if (strcmp
					  ((opname + 7),
					   "x_zoom_level")) break;
				      *impl =
					 (gpointer) servant->vepv->
					 Nautilus_Zoomable_epv->
					 _get_max_zoom_level;
				      return (ORBitSkeleton)
					 _ORBIT_skel_Nautilus_Zoomable__get_max_zoom_level;
				      break;
				   case 'i':
				      if (strcmp
					  ((opname + 7),
					   "n_zoom_level")) break;
				      *impl =
					 (gpointer) servant->vepv->
					 Nautilus_Zoomable_epv->
					 _get_min_zoom_level;
				      return (ORBitSkeleton)
					 _ORBIT_skel_Nautilus_Zoomable__get_min_zoom_level;
				      break;
				   default:
				      break;
				 }
				 break;
			      case 'p':
				 if (strcmp
				     ((opname + 6), "referred_zoom_levels"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Zoomable_epv->
				    _get_preferred_zoom_levels;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Zoomable__get_preferred_zoom_levels;
				 break;
			      case 'z':
				 if (strcmp((opname + 6), "oom_level"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Zoomable_epv->_get_zoom_level;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Zoomable__get_zoom_level;
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  case 's':
	     if (strcmp((opname + 2), "et_zoom_level"))
		break;
	     *impl =
		(gpointer) servant->vepv->Nautilus_Zoomable_epv->
		_set_zoom_level;
	     return (ORBitSkeleton)
		_ORBIT_skel_Nautilus_Zoomable__set_zoom_level;
	     break;
	  default:
	     break;
	}
	break;
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     case 'z':
	switch (opname[1]) {
	  case 'o':
	     switch (opname[2]) {
	       case 'o':
		  switch (opname[3]) {
		    case 'm':
		       switch (opname[4]) {
			 case '_':
			    switch (opname[5]) {
			      case 'i':
				 if (strcmp((opname + 6), "n"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Zoomable_epv->zoom_in;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Zoomable_zoom_in;
				 break;
			      case 'o':
				 if (strcmp((opname + 6), "ut"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Zoomable_epv->zoom_out;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Zoomable_zoom_out;
				 break;
			      case 't':
				 if (strcmp((opname + 6), "o_fit"))
				    break;
				 *impl =
				    (gpointer) servant->vepv->
				    Nautilus_Zoomable_epv->zoom_to_fit;
				 return (ORBitSkeleton)
				    _ORBIT_skel_Nautilus_Zoomable_zoom_to_fit;
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_Zoomable(CORBA_Object obj,
				    POA_Nautilus_Zoomable * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_Zoomable__classid] =
      servant->vepv->Nautilus_Zoomable_epv;
}

void
POA_Nautilus_Zoomable__init(PortableServer_Servant servant,
			    CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_Zoomable,
	 "IDL:Nautilus/Zoomable:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_Zoomable };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_Zoomable__classid)
      Nautilus_Zoomable__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_Zoomable__fini(PortableServer_Servant servant,
			    CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSkeleton
get_skel_Nautilus_ZoomableFrame(POA_Nautilus_ZoomableFrame * servant,
				GIOPRecvBuffer * _ORBIT_recv_buffer,
				gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 'f':
		  if (strcmp((opname + 3), ""))
		     break;
		  *impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
		  return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
		  break;
	       case 'p':
		  if (strcmp((opname + 3), "ort_zoom_level_changed"))
		     break;
		  *impl =
		     (gpointer) servant->vepv->Nautilus_ZoomableFrame_epv->
		     report_zoom_level_changed;
		  return (ORBitSkeleton)
		     _ORBIT_skel_Nautilus_ZoomableFrame_report_zoom_level_changed;
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_ZoomableFrame(CORBA_Object obj,
					 POA_Nautilus_ZoomableFrame * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_ZoomableFrame__classid] =
      servant->vepv->Nautilus_ZoomableFrame_epv;
}

void
POA_Nautilus_ZoomableFrame__init(PortableServer_Servant servant,
				 CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_ZoomableFrame,
	 "IDL:Nautilus/ZoomableFrame:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_ZoomableFrame

      };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_ZoomableFrame__classid)
      Nautilus_ZoomableFrame__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_ZoomableFrame__fini(PortableServer_Servant servant,
				 CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSkeleton
get_skel_Nautilus_HistoryFrame(POA_Nautilus_HistoryFrame * servant,
			       GIOPRecvBuffer * _ORBIT_recv_buffer,
			       gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'g':
	if (strcmp((opname + 1), "et_history_list"))
	   break;
	*impl =
	   (gpointer) servant->vepv->Nautilus_HistoryFrame_epv->
	   get_history_list;
	return (ORBitSkeleton)
	   _ORBIT_skel_Nautilus_HistoryFrame_get_history_list;
	break;
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Nautilus_HistoryFrame(CORBA_Object obj,
					POA_Nautilus_HistoryFrame * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Nautilus_HistoryFrame__classid] =
      servant->vepv->Nautilus_HistoryFrame_epv;
}

void
POA_Nautilus_HistoryFrame__init(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Nautilus_HistoryFrame,
	 "IDL:Nautilus/HistoryFrame:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Nautilus_HistoryFrame

      };
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Nautilus_HistoryFrame__classid)
      Nautilus_HistoryFrame__classid = ORBit_register_class(&class_info);
}

void
POA_Nautilus_HistoryFrame__fini(PortableServer_Servant servant,
				CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
