/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "trilobite-eazel-time-service.h"

void
_ORBIT_Trilobite_Eazel_Time_NotPermitted_marshal(GIOPSendBuffer *
						 _ORBIT_send_buffer,
						 CORBA_Environment * ev)
{
}

void
_ORBIT_Trilobite_Eazel_Time_CannotSet_marshal(GIOPSendBuffer *
					      _ORBIT_send_buffer,
					      CORBA_Environment * ev)
{
}
void
_ORBIT_Trilobite_Eazel_Time_CannotGetTime_marshal(GIOPSendBuffer *
						  _ORBIT_send_buffer,
						  CORBA_Environment * ev)
{
   register CORBA_unsigned_long _ORBIT_tmpvar_0;
   CORBA_unsigned_long _ORBIT_tmpvar_1;
   register CORBA_unsigned_long _ORBIT_tmpvar_2;
   CORBA_unsigned_long _ORBIT_tmpvar_3;
   Trilobite_Eazel_Time_CannotGetTime *_ORBIT_exdata = ev->_params;

   _ORBIT_tmpvar_1 = strlen((*_ORBIT_exdata).url) + 1;
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				    4);
   giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer),
					&(_ORBIT_tmpvar_1),
					sizeof(_ORBIT_tmpvar_1));
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				  ((*_ORBIT_exdata).url),
				  sizeof((*_ORBIT_exdata).
					 url[_ORBIT_tmpvar_0]) *
				  _ORBIT_tmpvar_1);
   _ORBIT_tmpvar_3 = strlen((*_ORBIT_exdata).reason) + 1;
   giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				    4);
   giop_send_buffer_append_mem_indirect(GIOP_SEND_BUFFER(_ORBIT_send_buffer),
					&(_ORBIT_tmpvar_3),
					sizeof(_ORBIT_tmpvar_3));
   giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				  ((*_ORBIT_exdata).reason),
				  sizeof((*_ORBIT_exdata).
					 reason[_ORBIT_tmpvar_2]) *
				  _ORBIT_tmpvar_3);
}

void
_ORBIT_skel_Trilobite_Eazel_Time_set_max_difference(POA_Trilobite_Eazel_Time *
						    _ORBIT_servant,
						    GIOPRecvBuffer *
						    _ORBIT_recv_buffer,
						    CORBA_Environment * ev,
						    void
						    (*_impl_set_max_difference)
						    (PortableServer_Servant
						     _servant,
						     const CORBA_long maxd,
						     CORBA_Environment * ev))
{
   CORBA_long maxd;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (maxd))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));} else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 maxd = *((CORBA_long *) _ORBIT_curptr);
      }
   }
   _impl_set_max_difference(_ORBIT_servant, maxd, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Trilobite_Eazel_Time_set_time_url(POA_Trilobite_Eazel_Time *
					      _ORBIT_servant,
					      GIOPRecvBuffer *
					      _ORBIT_recv_buffer,
					      CORBA_Environment * ev,
					      void (*_impl_set_time_url)
					      (PortableServer_Servant
					       _servant,
					       const CORBA_char * url,
					       CORBA_Environment * ev))
{
   CORBA_char *url;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      CORBA_unsigned_long _ORBIT_tmpvar_3;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_3))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 url = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(url[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_3 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 url = (void *) _ORBIT_curptr;
	 _ORBIT_curptr += sizeof(url[_ORBIT_tmpvar_2]) * _ORBIT_tmpvar_3;
      }
   }
   _impl_set_time_url(_ORBIT_servant, url, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Trilobite_Eazel_Time_check_time(POA_Trilobite_Eazel_Time *
					    _ORBIT_servant,
					    GIOPRecvBuffer *
					    _ORBIT_recv_buffer,
					    CORBA_Environment * ev,
					    CORBA_unsigned_long
					    (*_impl_check_time)
					    (PortableServer_Servant _servant,
					     CORBA_Environment * ev))
{
   CORBA_unsigned_long _ORBIT_retval;

   _ORBIT_retval = _impl_check_time(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	    giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					     (_ORBIT_send_buffer), 4);
	    {
	       guchar *_ORBIT_t;

	       _ORBIT_t = alloca(sizeof(_ORBIT_retval));
	       memcpy(_ORBIT_t, &(_ORBIT_retval), sizeof(_ORBIT_retval));
	       giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					      (_ORBIT_send_buffer),
					      (_ORBIT_t),
					      sizeof(_ORBIT_retval));
	    }
	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       = { {(const CORBA_TypeCode)
		    &TC_Trilobite_Eazel_Time_CannotGetTime_struct,
		    (gpointer)
		    _ORBIT_Trilobite_Eazel_Time_CannotGetTime_marshal},
	       {CORBA_OBJECT_NIL, NULL} };

	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
void
_ORBIT_skel_Trilobite_Eazel_Time_update_time(POA_Trilobite_Eazel_Time *
					     _ORBIT_servant,
					     GIOPRecvBuffer *
					     _ORBIT_recv_buffer,
					     CORBA_Environment * ev,
					     void (*_impl_update_time)
					     (PortableServer_Servant _servant,
					      CORBA_Environment * ev))
{
   _impl_update_time(_ORBIT_servant, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else if (ev->_major == CORBA_USER_EXCEPTION) {
	    static const ORBit_exception_marshal_info _ORBIT_user_exceptions[]
	       = { {(const CORBA_TypeCode)
		    &TC_Trilobite_Eazel_Time_NotPermitted_struct,
		    (gpointer)
		    _ORBIT_Trilobite_Eazel_Time_NotPermitted_marshal},
	       {(const CORBA_TypeCode)
		&TC_Trilobite_Eazel_Time_CannotGetTime_struct,
		(gpointer) _ORBIT_Trilobite_Eazel_Time_CannotGetTime_marshal},
	       {CORBA_OBJECT_NIL, NULL} };

	    ORBit_send_user_exception(_ORBIT_send_buffer, ev,
				      _ORBIT_user_exceptions);
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_Trilobite_Eazel_Time(POA_Trilobite_Eazel_Time * servant,
			      GIOPRecvBuffer * _ORBIT_recv_buffer,
			      gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'c':
	if (strcmp((opname + 1), "heck_time"))
	   break;
	*impl =
	   (gpointer) servant->vepv->Trilobite_Eazel_Time_epv->check_time;
	return (ORBitSkeleton) _ORBIT_skel_Trilobite_Eazel_Time_check_time;
	break;
     case 'q':
	if (strcmp((opname + 1), "uery_interface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->query_interface;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_query_interface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_ref;
	break;
     case 's':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case '_':
		       switch (opname[4]) {
			 case 'm':
			    if (strcmp((opname + 5), "ax_difference"))
			       break;
			    *impl =
			       (gpointer) servant->vepv->
			       Trilobite_Eazel_Time_epv->set_max_difference;
			    return (ORBitSkeleton)
			       _ORBIT_skel_Trilobite_Eazel_Time_set_max_difference;
			    break;
			 case 't':
			    if (strcmp((opname + 5), "ime_url"))
			       break;
			    *impl =
			       (gpointer) servant->vepv->
			       Trilobite_Eazel_Time_epv->set_time_url;
			    return (ORBitSkeleton)
			       _ORBIT_skel_Trilobite_Eazel_Time_set_time_url;
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'u':
	switch (opname[1]) {
	  case 'n':
	     if (strcmp((opname + 2), "ref"))
		break;
	     *impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	     return (ORBitSkeleton) _ORBIT_skel_Bonobo_Unknown_unref;
	     break;
	  case 'p':
	     if (strcmp((opname + 2), "date_time"))
		break;
	     *impl =
		(gpointer) servant->vepv->Trilobite_Eazel_Time_epv->
		update_time;
	     return (ORBitSkeleton)
		_ORBIT_skel_Trilobite_Eazel_Time_update_time;
	     break;
	  default:
	     break;
	}
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_Trilobite_Eazel_Time(CORBA_Object obj,
				       POA_Trilobite_Eazel_Time * servant)
{
   obj->vepv[Bonobo_Unknown__classid] = servant->vepv->Bonobo_Unknown_epv;
   obj->vepv[Trilobite_Eazel_Time__classid] =
      servant->vepv->Trilobite_Eazel_Time_epv;
}

void
POA_Trilobite_Eazel_Time__init(PortableServer_Servant servant,
			       CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_Trilobite_Eazel_Time,
	 "IDL:Trilobite/Eazel/Time:1.0",
	 (ORBit_local_objref_init) & init_local_objref_Trilobite_Eazel_Time };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!Trilobite_Eazel_Time__classid)
      Trilobite_Eazel_Time__classid = ORBit_register_class(&class_info);
}

void
POA_Trilobite_Eazel_Time__fini(PortableServer_Servant servant,
			       CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
