/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "trilobite-eazel-time-service.h"

#if ( (TC_IMPL_TC_Trilobite_Eazel_Time_0 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_1 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_2 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_3 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_4 == 'o') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_5 == 'b') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_6 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_7 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_8 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_9 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_10 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_11 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_12 == 'z') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_13 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_14 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_15 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_16 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_17 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_18 == 'm') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_19 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_20 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_21 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_22 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_23 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_24 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_25 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_26 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_27 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_Time)
#define TC_DEF_TC_Trilobite_Eazel_Time 1
const struct CORBA_TypeCode_struct TC_Trilobite_Eazel_Time_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Time", "IDL:Trilobite/Eazel/Time:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_0 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_1 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_2 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_3 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_4 == 'o') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_5 == 'b') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_6 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_7 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_8 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_9 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_10 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_11 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_12 == 'z') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_13 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_14 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_15 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_16 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_17 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_18 == 'm') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_19 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_20 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_21 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_22 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_23 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_24 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_25 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_26 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_NotPermitted_27 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_Time_NotPermitted)
#define TC_DEF_TC_Trilobite_Eazel_Time_NotPermitted 1
const struct CORBA_TypeCode_struct TC_Trilobite_Eazel_Time_NotPermitted_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "NotPermitted",
      "IDL:Trilobite/Eazel/Time/NotPermitted:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_0 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_1 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_2 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_3 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_4 == 'o') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_5 == 'b') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_6 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_7 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_8 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_9 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_10 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_11 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_12 == 'z') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_13 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_14 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_15 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_16 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_17 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_18 == 'm') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_19 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_20 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_21 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_22 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_23 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_24 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_25 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_26 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotSet_27 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_Time_CannotSet)
#define TC_DEF_TC_Trilobite_Eazel_Time_CannotSet 1
const struct CORBA_TypeCode_struct TC_Trilobite_Eazel_Time_CannotSet_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_except, "CannotSet", "IDL:Trilobite/Eazel/Time/CannotSet:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_0 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_1 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_2 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_3 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_4 == 'o') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_5 == 'b') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_6 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_7 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_8 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_9 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_10 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_11 == 'a') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_12 == 'z') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_13 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_14 == 'l') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_15 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_16 == 't') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_17 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_18 == 'm') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_19 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_20 == '_') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_21 == 's') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_22 == 'e') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_23 == 'r') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_24 == 'v') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_25 == 'i') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_26 == 'c') \
&& (TC_IMPL_TC_Trilobite_Eazel_Time_CannotGetTime_27 == 'e') \
) && !defined(TC_DEF_TC_Trilobite_Eazel_Time_CannotGetTime)
#define TC_DEF_TC_Trilobite_Eazel_Time_CannotGetTime 1
static const char *anon_subnames_array13[] = { "url", "reason" };
static const CORBA_TypeCode anon_subtypes_array14[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct
   TC_Trilobite_Eazel_Time_CannotGetTime_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "CannotGetTime",
      "IDL:Trilobite/Eazel/Time/CannotGetTime:1.0",
   0, 2,
   (const char **) anon_subnames_array13,
   (CORBA_TypeCode *) anon_subtypes_array14,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
gpointer
Trilobite_Eazel_Time_NotPermitted__free(gpointer mem, gpointer dat,
					CORBA_boolean free_strings)
{
   Trilobite_Eazel_Time_NotPermitted *var = mem;

   return (gpointer) (var + 1);
}

gpointer
Trilobite_Eazel_Time_CannotSet__free(gpointer mem, gpointer dat,
				     CORBA_boolean free_strings)
{
   Trilobite_Eazel_Time_CannotSet *var = mem;

   return (gpointer) (var + 1);
}

gpointer
Trilobite_Eazel_Time_CannotGetTime__free(gpointer mem, gpointer dat,
					 CORBA_boolean free_strings)
{
   Trilobite_Eazel_Time_CannotGetTime *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->url), NULL, free_strings);
   }
   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

Trilobite_Eazel_Time_CannotGetTime *
Trilobite_Eazel_Time_CannotGetTime__alloc(void)
{
   Trilobite_Eazel_Time_CannotGetTime *retval;

   retval =
      ORBit_alloc(sizeof(Trilobite_Eazel_Time_CannotGetTime),
		  (ORBit_free_childvals)
		  Trilobite_Eazel_Time_CannotGetTime__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->url), '\0', sizeof(retval->url));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   return retval;
}

CORBA_unsigned_long Trilobite_Eazel_Time__classid = 0;
