/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "nautilus-shell-interface.h"

#if ( (TC_IMPL_TC_Nautilus_URI_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_URI_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_URI_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_URI_3 == 't') \
&& (TC_IMPL_TC_Nautilus_URI_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_URI_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_URI_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_URI_7 == 's') \
&& (TC_IMPL_TC_Nautilus_URI_8 == '_') \
&& (TC_IMPL_TC_Nautilus_URI_9 == 's') \
&& (TC_IMPL_TC_Nautilus_URI_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_URI_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_URI_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_URI_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_URI_14 == '_') \
&& (TC_IMPL_TC_Nautilus_URI_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_URI_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_URI_17 == 't') \
&& (TC_IMPL_TC_Nautilus_URI_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_URI_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_URI_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_URI_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_URI_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_URI_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_URI)
#define TC_DEF_TC_Nautilus_URI 1
static const CORBA_TypeCode anon_subtypes_array7[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_URI_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "URI", "IDL:Nautilus/URI:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array7,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_0 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_2 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_3 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_4 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_5 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_6 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_7 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_9 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_10 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_11 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_12 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_13 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_14 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_16 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_17 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_18 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_19 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_20 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_21 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_22 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_23 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_Nautilus_URI)
#define TC_DEF_TC_CORBA_sequence_Nautilus_URI 1
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_Nautilus_URI_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_Nautilus_URI_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array11,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_0 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_2 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_3 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_4 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_5 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_6 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_7 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_9 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_10 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_11 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_12 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_13 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_14 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_16 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_17 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_18 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_19 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_20 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_21 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_22 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_URI_23 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_Nautilus_URI)
#define TC_DEF_TC_CORBA_sequence_Nautilus_URI 1
static const CORBA_TypeCode anon_subtypes_array20[] =
   { (CORBA_TypeCode) & TC_Nautilus_URI_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_Nautilus_URI_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array20,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_URIList_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_URIList_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_URIList_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_URIList_3 == 't') \
&& (TC_IMPL_TC_Nautilus_URIList_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_URIList_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_URIList_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_URIList_7 == 's') \
&& (TC_IMPL_TC_Nautilus_URIList_8 == '_') \
&& (TC_IMPL_TC_Nautilus_URIList_9 == 's') \
&& (TC_IMPL_TC_Nautilus_URIList_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_URIList_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_URIList_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_URIList_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_URIList_14 == '_') \
&& (TC_IMPL_TC_Nautilus_URIList_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_URIList_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_URIList_17 == 't') \
&& (TC_IMPL_TC_Nautilus_URIList_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_URIList_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_URIList_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_URIList_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_URIList_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_URIList_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_URIList)
#define TC_DEF_TC_Nautilus_URIList 1
static const CORBA_TypeCode anon_subtypes_array24[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_Nautilus_URI_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_URIList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "URIList", "IDL:Nautilus/URIList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array24,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_View_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_View_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_View_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_View_3 == 't') \
&& (TC_IMPL_TC_Nautilus_View_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_View_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_View_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_View_7 == 's') \
&& (TC_IMPL_TC_Nautilus_View_8 == '_') \
&& (TC_IMPL_TC_Nautilus_View_9 == 's') \
&& (TC_IMPL_TC_Nautilus_View_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_View_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_View_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_View_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_View_14 == '_') \
&& (TC_IMPL_TC_Nautilus_View_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_View_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_View_17 == 't') \
&& (TC_IMPL_TC_Nautilus_View_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_View_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_View_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_View_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_View_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_View_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_View)
#define TC_DEF_TC_Nautilus_View 1
const struct CORBA_TypeCode_struct TC_Nautilus_View_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "View", "IDL:Nautilus/View:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_ViewFrame_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_3 == 't') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_7 == 's') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_8 == '_') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_9 == 's') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_14 == '_') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_17 == 't') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_ViewFrame_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_ViewFrame)
#define TC_DEF_TC_Nautilus_ViewFrame 1
const struct CORBA_TypeCode_struct TC_Nautilus_ViewFrame_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "ViewFrame", "IDL:Nautilus/ViewFrame:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_ZoomLevel_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_3 == 't') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_7 == 's') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_8 == '_') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_9 == 's') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_14 == '_') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_17 == 't') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_ZoomLevel_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_ZoomLevel)
#define TC_DEF_TC_Nautilus_ZoomLevel 1
static const CORBA_TypeCode anon_subtypes_array41[] =
   { (CORBA_TypeCode) & TC_CORBA_double_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_ZoomLevel_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "ZoomLevel", "IDL:Nautilus/ZoomLevel:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array41,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_0 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_2 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_3 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_4 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_5 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_6 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_7 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_9 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_10 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_11 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_12 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_13 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_14 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_16 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_17 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_18 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_19 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_20 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_21 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_22 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_23 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_Nautilus_ZoomLevel)
#define TC_DEF_TC_CORBA_sequence_Nautilus_ZoomLevel 1
static const CORBA_TypeCode anon_subtypes_array45[] =
   { (CORBA_TypeCode) & TC_Nautilus_ZoomLevel_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_Nautilus_ZoomLevel_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array45,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_0 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_2 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_3 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_4 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_5 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_6 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_7 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_9 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_10 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_11 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_12 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_13 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_14 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_16 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_17 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_18 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_19 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_20 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_21 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_22 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_ZoomLevel_23 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_Nautilus_ZoomLevel)
#define TC_DEF_TC_CORBA_sequence_Nautilus_ZoomLevel 1
static const CORBA_TypeCode anon_subtypes_array54[] =
   { (CORBA_TypeCode) & TC_Nautilus_ZoomLevel_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_Nautilus_ZoomLevel_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array54,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_ZoomLevelList_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_3 == 't') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_7 == 's') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_8 == '_') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_9 == 's') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_14 == '_') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_17 == 't') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_ZoomLevelList_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_ZoomLevelList)
#define TC_DEF_TC_Nautilus_ZoomLevelList 1
static const CORBA_TypeCode anon_subtypes_array58[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_Nautilus_ZoomLevel_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_ZoomLevelList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "ZoomLevelList", "IDL:Nautilus/ZoomLevelList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array58,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_Zoomable_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_Zoomable_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_Zoomable_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_Zoomable_3 == 't') \
&& (TC_IMPL_TC_Nautilus_Zoomable_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_Zoomable_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_Zoomable_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_Zoomable_7 == 's') \
&& (TC_IMPL_TC_Nautilus_Zoomable_8 == '_') \
&& (TC_IMPL_TC_Nautilus_Zoomable_9 == 's') \
&& (TC_IMPL_TC_Nautilus_Zoomable_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_Zoomable_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_Zoomable_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_Zoomable_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_Zoomable_14 == '_') \
&& (TC_IMPL_TC_Nautilus_Zoomable_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_Zoomable_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_Zoomable_17 == 't') \
&& (TC_IMPL_TC_Nautilus_Zoomable_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_Zoomable_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_Zoomable_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_Zoomable_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_Zoomable_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_Zoomable_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_Zoomable)
#define TC_DEF_TC_Nautilus_Zoomable 1
const struct CORBA_TypeCode_struct TC_Nautilus_Zoomable_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Zoomable", "IDL:Nautilus/Zoomable:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_ZoomableFrame_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_3 == 't') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_7 == 's') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_8 == '_') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_9 == 's') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_14 == '_') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_17 == 't') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_ZoomableFrame_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_ZoomableFrame)
#define TC_DEF_TC_Nautilus_ZoomableFrame 1
const struct CORBA_TypeCode_struct TC_Nautilus_ZoomableFrame_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "ZoomableFrame", "IDL:Nautilus/ZoomableFrame:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_HistoryItem_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_3 == 't') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_7 == 's') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_8 == '_') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_9 == 's') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_14 == '_') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_17 == 't') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_HistoryItem_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_HistoryItem)
#define TC_DEF_TC_Nautilus_HistoryItem 1
static const char *anon_subnames_array69[] = { "title", "location" };
static const CORBA_TypeCode anon_subtypes_array70[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_Nautilus_URI_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_HistoryItem_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "HistoryItem", "IDL:Nautilus/HistoryItem:1.0",
   0, 2,
   (const char **) anon_subnames_array69,
   (CORBA_TypeCode *) anon_subtypes_array70,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_0 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_2 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_3 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_4 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_5 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_6 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_7 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_9 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_10 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_11 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_12 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_13 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_14 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_16 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_17 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_18 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_19 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_20 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_21 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_22 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_23 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_Nautilus_HistoryItem)
#define TC_DEF_TC_CORBA_sequence_Nautilus_HistoryItem 1
static const CORBA_TypeCode anon_subtypes_array74[] =
   { (CORBA_TypeCode) & TC_Nautilus_HistoryItem_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_Nautilus_HistoryItem_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array74,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_0 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_2 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_3 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_4 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_5 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_6 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_7 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_9 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_10 == 'h') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_11 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_12 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_13 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_14 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_16 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_17 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_18 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_19 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_20 == 'f') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_21 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_22 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_Nautilus_HistoryItem_23 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_Nautilus_HistoryItem)
#define TC_DEF_TC_CORBA_sequence_Nautilus_HistoryItem 1
static const CORBA_TypeCode anon_subtypes_array83[] =
   { (CORBA_TypeCode) & TC_Nautilus_HistoryItem_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_Nautilus_HistoryItem_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array83,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_HistoryList_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_HistoryList_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_HistoryList_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_HistoryList_3 == 't') \
&& (TC_IMPL_TC_Nautilus_HistoryList_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_HistoryList_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryList_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_HistoryList_7 == 's') \
&& (TC_IMPL_TC_Nautilus_HistoryList_8 == '_') \
&& (TC_IMPL_TC_Nautilus_HistoryList_9 == 's') \
&& (TC_IMPL_TC_Nautilus_HistoryList_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_HistoryList_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_HistoryList_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryList_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryList_14 == '_') \
&& (TC_IMPL_TC_Nautilus_HistoryList_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_HistoryList_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_HistoryList_17 == 't') \
&& (TC_IMPL_TC_Nautilus_HistoryList_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_HistoryList_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_HistoryList_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_HistoryList_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_HistoryList_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_HistoryList_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_HistoryList)
#define TC_DEF_TC_Nautilus_HistoryList 1
static const CORBA_TypeCode anon_subtypes_array87[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_Nautilus_HistoryItem_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_HistoryList_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "HistoryList", "IDL:Nautilus/HistoryList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array87,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_History_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_History_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_History_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_History_3 == 't') \
&& (TC_IMPL_TC_Nautilus_History_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_History_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_History_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_History_7 == 's') \
&& (TC_IMPL_TC_Nautilus_History_8 == '_') \
&& (TC_IMPL_TC_Nautilus_History_9 == 's') \
&& (TC_IMPL_TC_Nautilus_History_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_History_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_History_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_History_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_History_14 == '_') \
&& (TC_IMPL_TC_Nautilus_History_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_History_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_History_17 == 't') \
&& (TC_IMPL_TC_Nautilus_History_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_History_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_History_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_History_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_History_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_History_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_History)
#define TC_DEF_TC_Nautilus_History 1
static const char *anon_subnames_array90[] = { "list", "position" };
static const CORBA_TypeCode anon_subtypes_array91[] =
   { (CORBA_TypeCode) & TC_Nautilus_HistoryList_struct,
      (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_Nautilus_History_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_struct, "History", "IDL:Nautilus/History:1.0",
   0, 2,
   (const char **) anon_subnames_array90,
   (CORBA_TypeCode *) anon_subtypes_array91,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_HistoryFrame_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_3 == 't') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_7 == 's') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_8 == '_') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_9 == 's') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_14 == '_') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_17 == 't') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_HistoryFrame_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_HistoryFrame)
#define TC_DEF_TC_Nautilus_HistoryFrame 1
const struct CORBA_TypeCode_struct TC_Nautilus_HistoryFrame_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "HistoryFrame", "IDL:Nautilus/HistoryFrame:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_Nautilus_Shell_0 == 'n') \
&& (TC_IMPL_TC_Nautilus_Shell_1 == 'a') \
&& (TC_IMPL_TC_Nautilus_Shell_2 == 'u') \
&& (TC_IMPL_TC_Nautilus_Shell_3 == 't') \
&& (TC_IMPL_TC_Nautilus_Shell_4 == 'i') \
&& (TC_IMPL_TC_Nautilus_Shell_5 == 'l') \
&& (TC_IMPL_TC_Nautilus_Shell_6 == 'u') \
&& (TC_IMPL_TC_Nautilus_Shell_7 == 's') \
&& (TC_IMPL_TC_Nautilus_Shell_8 == '_') \
&& (TC_IMPL_TC_Nautilus_Shell_9 == 's') \
&& (TC_IMPL_TC_Nautilus_Shell_10 == 'h') \
&& (TC_IMPL_TC_Nautilus_Shell_11 == 'e') \
&& (TC_IMPL_TC_Nautilus_Shell_12 == 'l') \
&& (TC_IMPL_TC_Nautilus_Shell_13 == 'l') \
&& (TC_IMPL_TC_Nautilus_Shell_14 == '_') \
&& (TC_IMPL_TC_Nautilus_Shell_15 == 'i') \
&& (TC_IMPL_TC_Nautilus_Shell_16 == 'n') \
&& (TC_IMPL_TC_Nautilus_Shell_17 == 't') \
&& (TC_IMPL_TC_Nautilus_Shell_18 == 'e') \
&& (TC_IMPL_TC_Nautilus_Shell_19 == 'r') \
&& (TC_IMPL_TC_Nautilus_Shell_20 == 'f') \
&& (TC_IMPL_TC_Nautilus_Shell_21 == 'a') \
&& (TC_IMPL_TC_Nautilus_Shell_22 == 'c') \
&& (TC_IMPL_TC_Nautilus_Shell_23 == 'e') \
) && !defined(TC_DEF_TC_Nautilus_Shell)
#define TC_DEF_TC_Nautilus_Shell 1
const struct CORBA_TypeCode_struct TC_Nautilus_Shell_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Shell", "IDL:Nautilus/Shell:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_0 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_1 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_2 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_3 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_4 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_5 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_6 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_7 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_9 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_10 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_11 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_12 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_13 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_14 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_15 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_16 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_17 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_18 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_19 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_20 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_21 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_22 == 'c') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_URI_23 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_Nautilus_URI)
#define ORBIT_DEF_CORBA_sequence_Nautilus_URI 1

gpointer
CORBA_sequence_Nautilus_URI__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_Nautilus_URI *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_Nautilus_URI *
CORBA_sequence_Nautilus_URI__alloc(void)
{
   CORBA_sequence_Nautilus_URI *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_Nautilus_URI),
		  (ORBit_free_childvals) CORBA_sequence_Nautilus_URI__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

Nautilus_URI *
CORBA_sequence_Nautilus_URI_allocbuf(CORBA_unsigned_long len)
{
   Nautilus_URI *retval =
      ORBit_alloc(sizeof(Nautilus_URI) * len,
		  (ORBit_free_childvals) Nautilus_URI__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(Nautilus_URI) * len);
   return retval;
}
#endif

gpointer
Nautilus_URIList__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   return CORBA_sequence_Nautilus_URI__free(mem, dat, free_strings);
}

Nautilus_URIList *
Nautilus_URIList__alloc(void)
{
   return CORBA_sequence_Nautilus_URI__alloc();
}

CORBA_unsigned_long Nautilus_View__classid = 0;
CORBA_unsigned_long Nautilus_ViewFrame__classid = 0;

#if ( (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_0 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_1 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_2 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_3 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_4 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_5 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_6 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_7 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_9 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_10 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_11 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_12 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_13 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_14 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_15 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_16 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_17 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_18 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_19 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_20 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_21 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_22 == 'c') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_ZoomLevel_23 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_Nautilus_ZoomLevel)
#define ORBIT_DEF_CORBA_sequence_Nautilus_ZoomLevel 1

gpointer
CORBA_sequence_Nautilus_ZoomLevel__free(gpointer mem, gpointer dat,
					CORBA_boolean free_strings)
{
   CORBA_sequence_Nautilus_ZoomLevel *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_Nautilus_ZoomLevel *
CORBA_sequence_Nautilus_ZoomLevel__alloc(void)
{
   CORBA_sequence_Nautilus_ZoomLevel *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_Nautilus_ZoomLevel),
		  (ORBit_free_childvals)
		  CORBA_sequence_Nautilus_ZoomLevel__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

Nautilus_ZoomLevel *
CORBA_sequence_Nautilus_ZoomLevel_allocbuf(CORBA_unsigned_long len)
{
   Nautilus_ZoomLevel *retval =
      ORBit_alloc(sizeof(Nautilus_ZoomLevel) * len,
		  (ORBit_free_childvals) NULL, GUINT_TO_POINTER(len));

   return retval;
}
#endif

gpointer
Nautilus_ZoomLevelList__free(gpointer mem, gpointer dat,
			     CORBA_boolean free_strings)
{
   return CORBA_sequence_Nautilus_ZoomLevel__free(mem, dat, free_strings);
}

Nautilus_ZoomLevelList *
Nautilus_ZoomLevelList__alloc(void)
{
   return CORBA_sequence_Nautilus_ZoomLevel__alloc();
}

CORBA_unsigned_long Nautilus_Zoomable__classid = 0;
CORBA_unsigned_long Nautilus_ZoomableFrame__classid = 0;
gpointer
Nautilus_HistoryItem__free(gpointer mem, gpointer dat,
			   CORBA_boolean free_strings)
{
   Nautilus_HistoryItem *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->title), NULL, free_strings);
   }
   if (free_strings) {
      Nautilus_URI__free(&(var->location), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

Nautilus_HistoryItem *
Nautilus_HistoryItem__alloc(void)
{
   Nautilus_HistoryItem *retval;

   retval =
      ORBit_alloc(sizeof(Nautilus_HistoryItem),
		  (ORBit_free_childvals) Nautilus_HistoryItem__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->title), '\0', sizeof(retval->title));
   memset(&(retval->location), '\0', sizeof(retval->location));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_0 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_1 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_2 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_3 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_4 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_5 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_6 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_7 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_9 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_10 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_11 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_12 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_13 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_14 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_15 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_16 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_17 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_18 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_19 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_20 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_21 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_22 == 'c') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_23 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_Nautilus_HistoryItem)
#define ORBIT_DEF_CORBA_sequence_Nautilus_HistoryItem 1

gpointer
CORBA_sequence_Nautilus_HistoryItem__free(gpointer mem, gpointer dat,
					  CORBA_boolean free_strings)
{
   CORBA_sequence_Nautilus_HistoryItem *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_Nautilus_HistoryItem *
CORBA_sequence_Nautilus_HistoryItem__alloc(void)
{
   CORBA_sequence_Nautilus_HistoryItem *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_Nautilus_HistoryItem),
		  (ORBit_free_childvals)
		  CORBA_sequence_Nautilus_HistoryItem__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

Nautilus_HistoryItem *
CORBA_sequence_Nautilus_HistoryItem_allocbuf(CORBA_unsigned_long len)
{
   Nautilus_HistoryItem *retval =
      ORBit_alloc(sizeof(Nautilus_HistoryItem) * len,
		  (ORBit_free_childvals) Nautilus_HistoryItem__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(Nautilus_HistoryItem) * len);
   return retval;
}
#endif

gpointer
Nautilus_HistoryList__free(gpointer mem, gpointer dat,
			   CORBA_boolean free_strings)
{
   return CORBA_sequence_Nautilus_HistoryItem__free(mem, dat, free_strings);
}

Nautilus_HistoryList *
Nautilus_HistoryList__alloc(void)
{
   return CORBA_sequence_Nautilus_HistoryItem__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_0 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_1 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_2 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_3 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_4 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_5 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_6 == 'u') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_7 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_9 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_10 == 'h') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_11 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_12 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_13 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_14 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_15 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_16 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_17 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_18 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_19 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_20 == 'f') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_21 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_22 == 'c') \
&& (ORBIT_IMPL_CORBA_sequence_Nautilus_HistoryItem_23 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_Nautilus_HistoryItem)
#define ORBIT_DEF_CORBA_sequence_Nautilus_HistoryItem 1

gpointer
CORBA_sequence_Nautilus_HistoryItem__free(gpointer mem, gpointer dat,
					  CORBA_boolean free_strings)
{
   CORBA_sequence_Nautilus_HistoryItem *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_Nautilus_HistoryItem *
CORBA_sequence_Nautilus_HistoryItem__alloc(void)
{
   CORBA_sequence_Nautilus_HistoryItem *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_Nautilus_HistoryItem),
		  (ORBit_free_childvals)
		  CORBA_sequence_Nautilus_HistoryItem__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

Nautilus_HistoryItem *
CORBA_sequence_Nautilus_HistoryItem_allocbuf(CORBA_unsigned_long len)
{
   Nautilus_HistoryItem *retval =
      ORBit_alloc(sizeof(Nautilus_HistoryItem) * len,
		  (ORBit_free_childvals) Nautilus_HistoryItem__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(Nautilus_HistoryItem) * len);
   return retval;
}
#endif

gpointer
Nautilus_History__free(gpointer mem, gpointer dat, CORBA_boolean free_strings)
{
   Nautilus_History *var = mem;

   {
      Nautilus_HistoryList__free(&(var->list), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}

Nautilus_History *
Nautilus_History__alloc(void)
{
   Nautilus_History *retval;

   retval =
      ORBit_alloc(sizeof(Nautilus_History),
		  (ORBit_free_childvals) Nautilus_History__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->list), '\0', sizeof(retval->list));
   return retval;
}

CORBA_unsigned_long Nautilus_HistoryFrame__classid = 0;
CORBA_unsigned_long Nautilus_Shell__classid = 0;
