/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <glib.h>
#define ORBIT_IDL_SERIAL 9
#include <orb/orbit.h>

#ifndef GNOME_Desktop_FileOperationService_H
#define GNOME_Desktop_FileOperationService_H 1
#ifdef __cplusplus
extern "C"
{
#endif				/* __cplusplus */

/** typedefs **/
#include <liboaf/oaf-factory.h>
#include <liboaf/oaf-factory-suppress.h>
#include <bonobo/Bonobo.h>
#if !defined(ORBIT_DECL_GNOME_Desktop_FileOperationService) && !defined(_GNOME_Desktop_FileOperationService_defined)
#define ORBIT_DECL_GNOME_Desktop_FileOperationService 1
#define _GNOME_Desktop_FileOperationService_defined 1
#define GNOME_Desktop_FileOperationService__free CORBA_Object__free
   typedef CORBA_Object GNOME_Desktop_FileOperationService;
   extern CORBA_unsigned_long GNOME_Desktop_FileOperationService__classid;
#if !defined(TC_IMPL_TC_GNOME_Desktop_FileOperationService_0)
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_0 'G'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_1 'N'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_2 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_3 'M'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_4 'E'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_5 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_6 'D'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_7 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_8 's'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_9 'k'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_10 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_11 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_12 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_13 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_14 'F'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_15 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_16 'l'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_17 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_18 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_19 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_20 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_21 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_22 'a'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_23 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_24 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_25 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_26 'n'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_27 'S'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_28 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_29 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_30 'v'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_31 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_32 'c'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_33 'e'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Desktop_FileOperationService_struct;
#define TC_GNOME_Desktop_FileOperationService ((CORBA_TypeCode)&TC_GNOME_Desktop_FileOperationService_struct)
#endif
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_string) && !defined(_CORBA_sequence_CORBA_string_defined)
#define ORBIT_DECL_CORBA_sequence_CORBA_string 1
#define _CORBA_sequence_CORBA_string_defined 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_0 'G'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_1 'N'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_2 'O'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_3 'M'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_4 'E'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_5 '_'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_6 'D'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_7 'e'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_8 's'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_9 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_10 't'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_11 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_12 'p'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_13 '_'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_14 'F'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_15 'i'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_16 'l'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_17 'e'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_18 'O'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_19 'p'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_20 'e'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_21 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_22 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_23 't'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_24 'i'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_25 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_26 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_27 'S'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_28 'e'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_29 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_30 'v'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_31 'i'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_32 'c'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_33 'e'
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_char **_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_string;
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_string_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_0 'G'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_1 'N'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_2 'O'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_3 'M'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_4 'E'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_5 '_'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_6 'D'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_7 'e'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_8 's'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_9 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_10 't'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_11 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_12 'p'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_13 '_'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_14 'F'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_15 'i'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_16 'l'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_17 'e'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_18 'O'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_19 'p'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_20 'e'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_21 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_22 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_23 't'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_24 'i'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_25 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_26 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_27 'S'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_28 'e'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_29 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_30 'v'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_31 'i'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_32 'c'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_33 'e'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_string_struct;
#define TC_CORBA_sequence_CORBA_string ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_string_struct)
#endif
   extern CORBA_sequence_CORBA_string
      *CORBA_sequence_CORBA_string__alloc(void);
   extern gpointer CORBA_sequence_CORBA_string__free(gpointer mem,
						     gpointer dat,
						     CORBA_boolean free_strings);	/* ORBit internal use */
   CORBA_char **CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len);
#endif
#if !defined(_GNOME_Desktop_FileOperationService_FileNameList_defined)
#define _GNOME_Desktop_FileOperationService_FileNameList_defined 1
   typedef CORBA_sequence_CORBA_string
      GNOME_Desktop_FileOperationService_FileNameList;
#if !defined(TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_0)
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_0 'G'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_1 'N'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_2 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_3 'M'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_4 'E'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_5 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_6 'D'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_7 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_8 's'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_9 'k'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_10 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_11 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_12 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_13 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_14 'F'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_15 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_16 'l'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_17 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_18 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_19 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_20 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_21 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_22 'a'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_23 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_24 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_25 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_26 'n'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_27 'S'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_28 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_29 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_30 'v'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_31 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_32 'c'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_33 'e'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Desktop_FileOperationService_FileNameList_struct;
#define TC_GNOME_Desktop_FileOperationService_FileNameList ((CORBA_TypeCode)&TC_GNOME_Desktop_FileOperationService_FileNameList_struct)
#endif
   extern GNOME_Desktop_FileOperationService_FileNameList
      *GNOME_Desktop_FileOperationService_FileNameList__alloc(void);
   extern gpointer
      GNOME_Desktop_FileOperationService_FileNameList__free(gpointer mem,
							    gpointer dat,
							    CORBA_boolean free_strings);	/* ORBit internal use */
#endif
#if !defined(_GNOME_Desktop_FileOperationService_XferOptions_defined)
#define _GNOME_Desktop_FileOperationService_XferOptions_defined 1
   typedef CORBA_unsigned_short
      GNOME_Desktop_FileOperationService_XferOptions;
#if !defined(TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_0)
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_0 'G'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_1 'N'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_2 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_3 'M'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_4 'E'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_5 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_6 'D'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_7 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_8 's'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_9 'k'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_10 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_11 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_12 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_13 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_14 'F'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_15 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_16 'l'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_17 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_18 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_19 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_20 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_21 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_22 'a'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_23 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_24 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_25 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_26 'n'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_27 'S'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_28 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_29 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_30 'v'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_31 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_32 'c'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_33 'e'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Desktop_FileOperationService_XferOptions_struct;
#define TC_GNOME_Desktop_FileOperationService_XferOptions ((CORBA_TypeCode)&TC_GNOME_Desktop_FileOperationService_XferOptions_struct)
#endif
#endif
#ifndef GNOME_Desktop_FileOperationService_XferOptionDefault
#define GNOME_Desktop_FileOperationService_XferOptionDefault 0
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionDefault */

#ifndef GNOME_Desktop_FileOperationService_XferOptionPreserve
#define GNOME_Desktop_FileOperationService_XferOptionPreserve 1
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionPreserve */

#ifndef GNOME_Desktop_FileOperationService_XferOptionFollowLinks
#define GNOME_Desktop_FileOperationService_XferOptionFollowLinks 2
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionFollowLinks */

#ifndef GNOME_Desktop_FileOperationService_XferOptionWithParents
#define GNOME_Desktop_FileOperationService_XferOptionWithParents 4
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionWithParents */

#ifndef GNOME_Desktop_FileOperationService_XferOptionRecursive
#define GNOME_Desktop_FileOperationService_XferOptionRecursive 8
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionRecursive */

#ifndef GNOME_Desktop_FileOperationService_XferOptionSameFS
#define GNOME_Desktop_FileOperationService_XferOptionSameFS 16
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionSameFS */

#ifndef GNOME_Desktop_FileOperationService_XferOptionSparseAlways
#define GNOME_Desktop_FileOperationService_XferOptionSparseAlways 32
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionSparseAlways */

#ifndef GNOME_Desktop_FileOperationService_XferOptionSparseNever
#define GNOME_Desktop_FileOperationService_XferOptionSparseNever 64
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionSparseNever */

#ifndef GNOME_Desktop_FileOperationService_XferOptionUpdateMode
#define GNOME_Desktop_FileOperationService_XferOptionUpdateMode 128
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionUpdateMode */

#ifndef GNOME_Desktop_FileOperationService_XferOptionRemoveSource
#define GNOME_Desktop_FileOperationService_XferOptionRemoveSource 256
#endif				/* !GNOME_Desktop_FileOperationService_XferOptionRemoveSource */

#if !defined(_GNOME_Desktop_FileOperationService_XferOverwriteMode_defined)
#define _GNOME_Desktop_FileOperationService_XferOverwriteMode_defined 1
   typedef enum
   {
      GNOME_Desktop_FileOperationService_XferOverwriteAbort,
      GNOME_Desktop_FileOperationService_XferOverwriteQuery,
      GNOME_Desktop_FileOperationService_XferOverwriteReplace,
      GNOME_Desktop_FileOperationService_XferOverwriteSkip
   }
   GNOME_Desktop_FileOperationService_XferOverwriteMode;
#if !defined(TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_0)
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_0 'G'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_1 'N'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_2 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_3 'M'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_4 'E'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_5 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_6 'D'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_7 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_8 's'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_9 'k'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_10 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_11 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_12 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_13 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_14 'F'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_15 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_16 'l'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_17 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_18 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_19 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_20 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_21 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_22 'a'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_23 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_24 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_25 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_26 'n'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_27 'S'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_28 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_29 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_30 'v'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_31 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_32 'c'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_33 'e'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_struct;
#define TC_GNOME_Desktop_FileOperationService_XferOverwriteMode ((CORBA_TypeCode)&TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_struct)
#endif
#endif
#if !defined(_GNOME_Desktop_FileOperationService_XferErrorMode_defined)
#define _GNOME_Desktop_FileOperationService_XferErrorMode_defined 1
   typedef enum
   {
      GNOME_Desktop_FileOperationService_XferErrorAbort,
      GNOME_Desktop_FileOperationService_XferErrorQuery
   }
   GNOME_Desktop_FileOperationService_XferErrorMode;
#if !defined(TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_0)
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_0 'G'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_1 'N'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_2 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_3 'M'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_4 'E'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_5 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_6 'D'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_7 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_8 's'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_9 'k'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_10 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_11 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_12 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_13 '_'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_14 'F'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_15 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_16 'l'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_17 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_18 'O'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_19 'p'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_20 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_21 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_22 'a'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_23 't'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_24 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_25 'o'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_26 'n'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_27 'S'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_28 'e'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_29 'r'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_30 'v'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_31 'i'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_32 'c'
#define TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_33 'e'
   extern const struct CORBA_TypeCode_struct
      TC_GNOME_Desktop_FileOperationService_XferErrorMode_struct;
#define TC_GNOME_Desktop_FileOperationService_XferErrorMode ((CORBA_TypeCode)&TC_GNOME_Desktop_FileOperationService_XferErrorMode_struct)
#endif
#endif

/** POA structures **/
   typedef struct
   {
      void *_private;
      void (*xfer) (PortableServer_Servant _servant,
		    const CORBA_char * source_directory_uri,
		    const GNOME_Desktop_FileOperationService_FileNameList *
		    source_file_names,
		    const CORBA_char * target_directory_uri,
		    const GNOME_Desktop_FileOperationService_FileNameList *
		    target_file_names,
		    const GNOME_Desktop_FileOperationService_XferOptions
		    options,
		    const GNOME_Desktop_FileOperationService_XferErrorMode
		    error_mode,
		    const GNOME_Desktop_FileOperationService_XferOverwriteMode
		    overwrite_mode, CORBA_Environment * ev);
   }
   POA_GNOME_Desktop_FileOperationService__epv;
   typedef struct
   {
      PortableServer_ServantBase__epv *_base_epv;
      POA_GNOME_Desktop_FileOperationService__epv
	 *GNOME_Desktop_FileOperationService_epv;
   }
   POA_GNOME_Desktop_FileOperationService__vepv;
   typedef struct
   {
      void *_private;
      POA_GNOME_Desktop_FileOperationService__vepv *vepv;
   }
   POA_GNOME_Desktop_FileOperationService;
   extern void
      POA_GNOME_Desktop_FileOperationService__init(PortableServer_Servant
						   servant,
						   CORBA_Environment * ev);
   extern void
      POA_GNOME_Desktop_FileOperationService__fini(PortableServer_Servant
						   servant,
						   CORBA_Environment * ev);

/** prototypes **/
   void
      GNOME_Desktop_FileOperationService_xfer
      (GNOME_Desktop_FileOperationService _obj,
       const CORBA_char * source_directory_uri,
       const GNOME_Desktop_FileOperationService_FileNameList *
       source_file_names, const CORBA_char * target_directory_uri,
       const GNOME_Desktop_FileOperationService_FileNameList *
       target_file_names,
       const GNOME_Desktop_FileOperationService_XferOptions options,
       const GNOME_Desktop_FileOperationService_XferErrorMode error_mode,
       const GNOME_Desktop_FileOperationService_XferOverwriteMode
       overwrite_mode, CORBA_Environment * ev);

   void
      _ORBIT_skel_GNOME_Desktop_FileOperationService_xfer
      (POA_GNOME_Desktop_FileOperationService * _ORBIT_servant,
       GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
       void (*_impl_xfer) (PortableServer_Servant _servant,
			   const CORBA_char * source_directory_uri,
			   const
			   GNOME_Desktop_FileOperationService_FileNameList *
			   source_file_names,
			   const CORBA_char * target_directory_uri,
			   const
			   GNOME_Desktop_FileOperationService_FileNameList *
			   target_file_names,
			   const
			   GNOME_Desktop_FileOperationService_XferOptions
			   options,
			   const
			   GNOME_Desktop_FileOperationService_XferErrorMode
			   error_mode,
			   const
			   GNOME_Desktop_FileOperationService_XferOverwriteMode
			   overwrite_mode, CORBA_Environment * ev));
#ifdef __cplusplus
}
#endif				/* __cplusplus */

#endif
#undef ORBIT_IDL_SERIAL
