/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "GNOME_Desktop_FileOperationService.h"

void
_ORBIT_skel_GNOME_Desktop_FileOperationService_xfer
   (POA_GNOME_Desktop_FileOperationService * _ORBIT_servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, CORBA_Environment * ev,
    void (*_impl_xfer) (PortableServer_Servant _servant,
			const CORBA_char * source_directory_uri,
			const GNOME_Desktop_FileOperationService_FileNameList
			* source_file_names,
			const CORBA_char * target_directory_uri,
			const GNOME_Desktop_FileOperationService_FileNameList
			* target_file_names,
			const GNOME_Desktop_FileOperationService_XferOptions
			options,
			const GNOME_Desktop_FileOperationService_XferErrorMode
			error_mode,
			const
			GNOME_Desktop_FileOperationService_XferOverwriteMode
			overwrite_mode, CORBA_Environment * ev))
{
   CORBA_char *source_directory_uri;
   GNOME_Desktop_FileOperationService_FileNameList source_file_names =
      { 0, 0, NULL, CORBA_FALSE };
   CORBA_char *target_directory_uri;
   GNOME_Desktop_FileOperationService_FileNameList target_file_names =
      { 0, 0, NULL, CORBA_FALSE };
   GNOME_Desktop_FileOperationService_XferOptions options;
   GNOME_Desktop_FileOperationService_XferErrorMode error_mode;
   GNOME_Desktop_FileOperationService_XferOverwriteMode overwrite_mode;

   {				/* demarshalling */
      guchar *_ORBIT_curptr;
      register CORBA_unsigned_long _ORBIT_tmpvar_10;
      CORBA_unsigned_long _ORBIT_tmpvar_11;
      register CORBA_unsigned_long _ORBIT_tmpvar_12;
      register CORBA_unsigned_long _ORBIT_tmpvar_13;
      CORBA_unsigned_long _ORBIT_tmpvar_14;
      register CORBA_unsigned_long _ORBIT_tmpvar_15;
      CORBA_unsigned_long _ORBIT_tmpvar_16;
      register CORBA_unsigned_long _ORBIT_tmpvar_17;
      register CORBA_unsigned_long _ORBIT_tmpvar_18;
      CORBA_unsigned_long _ORBIT_tmpvar_19;

      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_11))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 source_directory_uri = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(source_directory_uri[_ORBIT_tmpvar_10]) * _ORBIT_tmpvar_11;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (source_file_names._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 source_file_names._buffer =
	    alloca(sizeof(source_file_names._buffer[_ORBIT_tmpvar_12]) *
		   source_file_names._length);
	 source_file_names._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_12 = 0;
	      _ORBIT_tmpvar_12 < source_file_names._length;
	      _ORBIT_tmpvar_12++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_14))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    source_file_names._buffer[_ORBIT_tmpvar_12] =
	       (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(source_file_names.
		      _buffer[_ORBIT_tmpvar_12][_ORBIT_tmpvar_13]) *
	       _ORBIT_tmpvar_14;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (_ORBIT_tmpvar_16))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 target_directory_uri = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(target_directory_uri[_ORBIT_tmpvar_15]) * _ORBIT_tmpvar_16;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (target_file_names._length))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	 _ORBIT_curptr += 4;
	 target_file_names._buffer =
	    alloca(sizeof(target_file_names._buffer[_ORBIT_tmpvar_17]) *
		   target_file_names._length);
	 target_file_names._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_17 = 0;
	      _ORBIT_tmpvar_17 < target_file_names._length;
	      _ORBIT_tmpvar_17++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    
	       (*((guint32 *) & (_ORBIT_tmpvar_19))) =
	       GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	    target_file_names._buffer[_ORBIT_tmpvar_17] =
	       (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(target_file_names.
		      _buffer[_ORBIT_tmpvar_17][_ORBIT_tmpvar_18]) *
	       _ORBIT_tmpvar_19;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 2);
	 
	    (*((guint16 *) & (options))) =
	    GUINT16_SWAP_LE_BE(*((guint16 *) _ORBIT_curptr));
	    _ORBIT_curptr += 2;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 
	    (*((guint32 *) & (error_mode))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
	    _ORBIT_curptr += 4;
	 (*((guint32 *) & (overwrite_mode))) =
	    GUINT32_SWAP_LE_BE(*((guint32 *) _ORBIT_curptr));
      } else {
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_11 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 source_directory_uri = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(source_directory_uri[_ORBIT_tmpvar_10]) * _ORBIT_tmpvar_11;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 source_file_names._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 source_file_names._buffer =
	    alloca(sizeof(source_file_names._buffer[_ORBIT_tmpvar_12]) *
		   source_file_names._length);
	 source_file_names._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_12 = 0;
	      _ORBIT_tmpvar_12 < source_file_names._length;
	      _ORBIT_tmpvar_12++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_14 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    source_file_names._buffer[_ORBIT_tmpvar_12] =
	       (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(source_file_names.
		      _buffer[_ORBIT_tmpvar_12][_ORBIT_tmpvar_13]) *
	       _ORBIT_tmpvar_14;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 _ORBIT_tmpvar_16 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 target_directory_uri = (void *) _ORBIT_curptr;
	 _ORBIT_curptr +=
	    sizeof(target_directory_uri[_ORBIT_tmpvar_15]) * _ORBIT_tmpvar_16;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 target_file_names._length = *((CORBA_unsigned_long *) _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 target_file_names._buffer =
	    alloca(sizeof(target_file_names._buffer[_ORBIT_tmpvar_17]) *
		   target_file_names._length);
	 target_file_names._release = CORBA_FALSE;
	 for (_ORBIT_tmpvar_17 = 0;
	      _ORBIT_tmpvar_17 < target_file_names._length;
	      _ORBIT_tmpvar_17++) {
	    _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	    _ORBIT_tmpvar_19 = *((CORBA_unsigned_long *) _ORBIT_curptr);
	    _ORBIT_curptr += 4;
	    target_file_names._buffer[_ORBIT_tmpvar_17] =
	       (void *) _ORBIT_curptr;
	    _ORBIT_curptr +=
	       sizeof(target_file_names.
		      _buffer[_ORBIT_tmpvar_17][_ORBIT_tmpvar_18]) *
	       _ORBIT_tmpvar_19;
	 }

	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 2);
	 options =
	    *((GNOME_Desktop_FileOperationService_XferOptions *)
	      _ORBIT_curptr);
	 _ORBIT_curptr += 2;
	 _ORBIT_curptr = ALIGN_ADDRESS(_ORBIT_curptr, 4);
	 error_mode =
	    *((GNOME_Desktop_FileOperationService_XferErrorMode *)
	      _ORBIT_curptr);
	 _ORBIT_curptr += 4;
	 overwrite_mode =
	    *((GNOME_Desktop_FileOperationService_XferOverwriteMode *)
	      _ORBIT_curptr);
      }
   }
   _impl_xfer(_ORBIT_servant, source_directory_uri, &(source_file_names),
	      target_directory_uri, &(target_file_names), options, error_mode,
	      overwrite_mode, ev);
   {				/* marshalling */
      register GIOPSendBuffer *_ORBIT_send_buffer;

      _ORBIT_send_buffer =
	 giop_send_reply_buffer_use(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer)->
				    connection, NULL,
				    _ORBIT_recv_buffer->message.u.request.
				    request_id, ev->_major);
      if (_ORBIT_send_buffer) {
	 if (ev->_major == CORBA_NO_EXCEPTION) {
	 } else
	    ORBit_send_system_exception(_ORBIT_send_buffer, ev);
	 giop_send_buffer_write(_ORBIT_send_buffer);
	 giop_send_buffer_unuse(_ORBIT_send_buffer);
      }
   }
}
static ORBitSkeleton
get_skel_GNOME_Desktop_FileOperationService
   (POA_GNOME_Desktop_FileOperationService * servant,
    GIOPRecvBuffer * _ORBIT_recv_buffer, gpointer * impl)
{
   gchar *opname = _ORBIT_recv_buffer->message.u.request.operation;

   switch (opname[0]) {
     case 'x':
	if (strcmp((opname + 1), "fer"))
	   break;
	*impl =
	   (gpointer) servant->vepv->GNOME_Desktop_FileOperationService_epv->
	   xfer;
	return (ORBitSkeleton)
	   _ORBIT_skel_GNOME_Desktop_FileOperationService_xfer;
	break;
     default:
	break;
   }
   return NULL;
}

static void
init_local_objref_GNOME_Desktop_FileOperationService(CORBA_Object obj,
						     POA_GNOME_Desktop_FileOperationService
						     * servant)
{
   obj->vepv[GNOME_Desktop_FileOperationService__classid] =
      servant->vepv->GNOME_Desktop_FileOperationService_epv;
}

void
POA_GNOME_Desktop_FileOperationService__init(PortableServer_Servant servant,
					     CORBA_Environment * env)
{
   static const PortableServer_ClassInfo class_info =
      { (ORBit_impl_finder) & get_skel_GNOME_Desktop_FileOperationService,
	 "IDL:GNOME/Desktop/FileOperationService:1.0",
	 (ORBit_local_objref_init) &
	 init_local_objref_GNOME_Desktop_FileOperationService };

   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBIT_OBJECT_KEY(((PortableServer_ServantBase *) servant)->_private)->
      class_info = (PortableServer_ClassInfo *) & class_info;
   if (!GNOME_Desktop_FileOperationService__classid)
      GNOME_Desktop_FileOperationService__classid =
	 ORBit_register_class(&class_info);
}

void
POA_GNOME_Desktop_FileOperationService__fini(PortableServer_Servant servant,
					     CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
