/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "GNOME_Desktop_FileOperationService.h"

#if ( (TC_IMPL_TC_GNOME_Desktop_FileOperationService_0 == 'G') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_1 == 'N') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_2 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_3 == 'M') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_4 == 'E') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_5 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_6 == 'D') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_7 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_8 == 's') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_9 == 'k') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_10 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_12 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_13 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_14 == 'F') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_15 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_16 == 'l') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_17 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_18 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_19 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_20 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_21 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_22 == 'a') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_23 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_24 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_25 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_26 == 'n') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_27 == 'S') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_28 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_29 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_30 == 'v') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_31 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_32 == 'c') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_33 == 'e') \
) && !defined(TC_DEF_TC_GNOME_Desktop_FileOperationService)
#define TC_DEF_TC_GNOME_Desktop_FileOperationService 1
const struct CORBA_TypeCode_struct
   TC_GNOME_Desktop_FileOperationService_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "FileOperationService",
      "IDL:GNOME/Desktop/FileOperationService:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'G') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'N') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'O') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'M') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'E') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'D') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_13 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_14 == 'F') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_16 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_17 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_18 == 'O') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_19 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_20 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_21 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_22 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_23 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_24 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_25 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_26 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_27 == 'S') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_28 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_29 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_30 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_31 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_32 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_33 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array6[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array6,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'G') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'N') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'O') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'M') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'E') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'D') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_12 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_13 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_14 == 'F') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_15 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_16 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_17 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_18 == 'O') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_19 == 'p') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_20 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_21 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_22 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_23 == 't') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_24 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_25 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_26 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_27 == 'S') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_28 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_29 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_30 == 'v') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_31 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_32 == 'c') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_33 == 'e') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array15[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   
      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array15,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_0 == 'G') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_1 == 'N') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_2 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_3 == 'M') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_4 == 'E') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_5 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_6 == 'D') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_7 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_8 == 's') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_9 == 'k') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_10 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_12 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_13 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_14 == 'F') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_15 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_16 == 'l') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_17 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_18 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_19 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_20 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_21 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_22 == 'a') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_23 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_24 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_25 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_26 == 'n') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_27 == 'S') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_28 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_29 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_30 == 'v') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_31 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_32 == 'c') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_FileNameList_33 == 'e') \
) && !defined(TC_DEF_TC_GNOME_Desktop_FileOperationService_FileNameList)
#define TC_DEF_TC_GNOME_Desktop_FileOperationService_FileNameList 1
static const CORBA_TypeCode anon_subtypes_array19[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct
   TC_GNOME_Desktop_FileOperationService_FileNameList_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "FileNameList",
      "IDL:GNOME/Desktop/FileOperationService/FileNameList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array19,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_0 == 'G') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_1 == 'N') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_2 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_3 == 'M') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_4 == 'E') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_5 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_6 == 'D') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_7 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_8 == 's') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_9 == 'k') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_10 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_12 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_13 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_14 == 'F') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_15 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_16 == 'l') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_17 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_18 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_19 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_20 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_21 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_22 == 'a') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_23 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_24 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_25 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_26 == 'n') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_27 == 'S') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_28 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_29 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_30 == 'v') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_31 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_32 == 'c') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOptions_33 == 'e') \
) && !defined(TC_DEF_TC_GNOME_Desktop_FileOperationService_XferOptions)
#define TC_DEF_TC_GNOME_Desktop_FileOperationService_XferOptions 1
static const CORBA_TypeCode anon_subtypes_array28[] =
   { (CORBA_TypeCode) & TC_CORBA_unsigned_short_struct };
const struct CORBA_TypeCode_struct
   TC_GNOME_Desktop_FileOperationService_XferOptions_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "XferOptions",
      "IDL:GNOME/Desktop/FileOperationService/XferOptions:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array28,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_0 == 'G') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_1 == 'N') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_2 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_3 == 'M') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_4 == 'E') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_5 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_6 == 'D') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_7 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_8 == 's') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_9 == 'k') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_10 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_12 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_13 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_14 == 'F') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_15 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_16 == 'l') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_17 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_18 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_19 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_20 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_21 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_22 == 'a') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_23 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_24 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_25 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_26 == 'n') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_27 == 'S') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_28 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_29 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_30 == 'v') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_31 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_32 == 'c') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_33 == 'e') \
) && !defined(TC_DEF_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode)
#define TC_DEF_TC_GNOME_Desktop_FileOperationService_XferOverwriteMode 1
static const char *anon_subnames_array31[] =
   { "XferOverwriteAbort", "XferOverwriteQuery", "XferOverwriteReplace",
      "XferOverwriteSkip" };
const struct CORBA_TypeCode_struct
   TC_GNOME_Desktop_FileOperationService_XferOverwriteMode_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "XferOverwriteMode",
      "IDL:GNOME/Desktop/FileOperationService/XferOverwriteMode:1.0",
   0, 4,
   (const char **) anon_subnames_array31,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_0 == 'G') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_1 == 'N') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_2 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_3 == 'M') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_4 == 'E') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_5 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_6 == 'D') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_7 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_8 == 's') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_9 == 'k') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_10 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_11 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_12 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_13 == '_') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_14 == 'F') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_15 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_16 == 'l') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_17 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_18 == 'O') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_19 == 'p') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_20 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_21 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_22 == 'a') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_23 == 't') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_24 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_25 == 'o') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_26 == 'n') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_27 == 'S') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_28 == 'e') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_29 == 'r') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_30 == 'v') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_31 == 'i') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_32 == 'c') \
&& (TC_IMPL_TC_GNOME_Desktop_FileOperationService_XferErrorMode_33 == 'e') \
) && !defined(TC_DEF_TC_GNOME_Desktop_FileOperationService_XferErrorMode)
#define TC_DEF_TC_GNOME_Desktop_FileOperationService_XferErrorMode 1
static const char *anon_subnames_array35[] =
   { "XferErrorAbort", "XferErrorQuery" };
const struct CORBA_TypeCode_struct
   TC_GNOME_Desktop_FileOperationService_XferErrorMode_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_enum, "XferErrorMode",
      "IDL:GNOME/Desktop/FileOperationService/XferErrorMode:1.0",
   0, 2,
   (const char **) anon_subnames_array35,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'G') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'N') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'O') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'M') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'E') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'D') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == 's') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == 'k') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_10 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_11 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_12 == 'p') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_13 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_14 == 'F') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_15 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_16 == 'l') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_17 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_18 == 'O') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_19 == 'p') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_20 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_21 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_22 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_23 == 't') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_24 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_25 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_26 == 'n') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_27 == 'S') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_28 == 'e') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_29 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_30 == 'v') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_31 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_32 == 'c') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_33 == 'e') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif

gpointer
GNOME_Desktop_FileOperationService_FileNameList__free(gpointer mem,
						      gpointer dat,
						      CORBA_boolean
						      free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}

GNOME_Desktop_FileOperationService_FileNameList *
GNOME_Desktop_FileOperationService_FileNameList__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

CORBA_unsigned_long GNOME_Desktop_FileOperationService__classid = 0;
