/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#include "GNOME_Desktop_FileOperationService.h"

void
GNOME_Desktop_FileOperationService_xfer(GNOME_Desktop_FileOperationService
					_obj,
					const CORBA_char *
					source_directory_uri,
					const
					GNOME_Desktop_FileOperationService_FileNameList
					* source_file_names,
					const CORBA_char *
					target_directory_uri,
					const
					GNOME_Desktop_FileOperationService_FileNameList
					* target_file_names,
					const
					GNOME_Desktop_FileOperationService_XferOptions
					options,
					const
					GNOME_Desktop_FileOperationService_XferErrorMode
					error_mode,
					const
					GNOME_Desktop_FileOperationService_XferOverwriteMode
					overwrite_mode,
					CORBA_Environment * ev)
{
   register GIOP_unsigned_long _ORBIT_request_id,
    _ORBIT_system_exception_minor;
   register CORBA_completion_status _ORBIT_completion_status;
   register GIOPSendBuffer *_ORBIT_send_buffer;
   register GIOPRecvBuffer *_ORBIT_recv_buffer;
   register GIOPConnection *_cnx;

   if (_obj->servant && _obj->vepv
       && GNOME_Desktop_FileOperationService__classid) {
      ((POA_GNOME_Desktop_FileOperationService__epv *) _obj->
       vepv[GNOME_Desktop_FileOperationService__classid])->xfer(_obj->servant,
								source_directory_uri,
								source_file_names,
								target_directory_uri,
								target_file_names,
								options,
								error_mode,
								overwrite_mode,
								ev);
      return;
   }
   _cnx = ORBit_object_get_connection(_obj);
 _ORBIT_retry_request:
   _ORBIT_send_buffer = NULL;
   _ORBIT_recv_buffer = NULL;
   _ORBIT_completion_status = CORBA_COMPLETED_NO;
   _ORBIT_request_id = GPOINTER_TO_UINT(alloca(0));
   {				/* marshalling */
      static const struct
      {
	 CORBA_unsigned_long len;
	 char opname[5];
      }
      _ORBIT_operation_name_data =
      {
      5, "xfer"};
      static const struct iovec _ORBIT_operation_vec =
	 { (gpointer) & _ORBIT_operation_name_data, 9 };
      register CORBA_unsigned_long _ORBIT_tmpvar_0;
      CORBA_unsigned_long _ORBIT_tmpvar_1;
      register CORBA_unsigned_long _ORBIT_tmpvar_2;
      register CORBA_unsigned_long _ORBIT_tmpvar_3;
      CORBA_unsigned_long _ORBIT_tmpvar_4;
      register CORBA_unsigned_long _ORBIT_tmpvar_5;
      CORBA_unsigned_long _ORBIT_tmpvar_6;
      register CORBA_unsigned_long _ORBIT_tmpvar_7;
      register CORBA_unsigned_long _ORBIT_tmpvar_8;
      CORBA_unsigned_long _ORBIT_tmpvar_9;

      _ORBIT_send_buffer =
	 giop_send_request_buffer_use(_cnx, NULL, _ORBIT_request_id,
				      CORBA_TRUE,
				      &(_obj->active_profile->object_key_vec),
				      &_ORBIT_operation_vec,
				      &ORBit_default_principal_iovec);

      _ORBIT_system_exception_minor = ex_CORBA_COMM_FAILURE;
      if (!_ORBIT_send_buffer)
	 goto _ORBIT_system_exception;
      _ORBIT_tmpvar_1 = strlen(source_directory_uri) + 1;
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
				       (_ORBIT_send_buffer), 4);
      {
	 guchar *_ORBIT_t;

	 _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_1));
	 memcpy(_ORBIT_t, &(_ORBIT_tmpvar_1), sizeof(_ORBIT_tmpvar_1));
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					(_ORBIT_send_buffer), (_ORBIT_t),
					sizeof(_ORBIT_tmpvar_1));
      }
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				     (source_directory_uri),
				     sizeof(source_directory_uri
					    [_ORBIT_tmpvar_0]) *
				     _ORBIT_tmpvar_1);
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
				       (_ORBIT_send_buffer), 4);
      {
	 guchar *_ORBIT_t;

	 _ORBIT_t = alloca(sizeof((*source_file_names)._length));
	 memcpy(_ORBIT_t, &((*source_file_names)._length),
		sizeof((*source_file_names)._length));
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					(_ORBIT_send_buffer), (_ORBIT_t),
					sizeof((*source_file_names)._length));
      }
      for (_ORBIT_tmpvar_2 = 0;
	   _ORBIT_tmpvar_2 < (*source_file_names)._length; _ORBIT_tmpvar_2++) {
	 _ORBIT_tmpvar_4 =
	    strlen((*source_file_names)._buffer[_ORBIT_tmpvar_2]) + 1;
	 giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					  (_ORBIT_send_buffer), 4);
	 {
	    guchar *_ORBIT_t;

	    _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_4));
	    memcpy(_ORBIT_t, &(_ORBIT_tmpvar_4), sizeof(_ORBIT_tmpvar_4));
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer), (_ORBIT_t),
					   sizeof(_ORBIT_tmpvar_4));
	 }
	 {
	    guchar *_ORBIT_t;

	    _ORBIT_t =
	       alloca(sizeof
		      ((*source_file_names).
		       _buffer[_ORBIT_tmpvar_2][_ORBIT_tmpvar_3]) *
		      _ORBIT_tmpvar_4);
	       memcpy(_ORBIT_t,
		      ((*source_file_names)._buffer[_ORBIT_tmpvar_2]),
		      sizeof((*source_file_names).
			     _buffer[_ORBIT_tmpvar_2][_ORBIT_tmpvar_3]) *
		      _ORBIT_tmpvar_4);
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer), (_ORBIT_t),
					   sizeof((*source_file_names).
						  _buffer[_ORBIT_tmpvar_2]
						  [_ORBIT_tmpvar_3]) *
					   _ORBIT_tmpvar_4);
	 }
      }

      _ORBIT_tmpvar_6 = strlen(target_directory_uri) + 1;
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
				       (_ORBIT_send_buffer), 4);
      {
	 guchar *_ORBIT_t;

	 _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_6));
	 memcpy(_ORBIT_t, &(_ORBIT_tmpvar_6), sizeof(_ORBIT_tmpvar_6));
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					(_ORBIT_send_buffer), (_ORBIT_t),
					sizeof(_ORBIT_tmpvar_6));
      }
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				     (target_directory_uri),
				     sizeof(target_directory_uri
					    [_ORBIT_tmpvar_5]) *
				     _ORBIT_tmpvar_6);
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
				       (_ORBIT_send_buffer), 4);
      {
	 guchar *_ORBIT_t;

	 _ORBIT_t = alloca(sizeof((*target_file_names)._length));
	 memcpy(_ORBIT_t, &((*target_file_names)._length),
		sizeof((*target_file_names)._length));
	 giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					(_ORBIT_send_buffer), (_ORBIT_t),
					sizeof((*target_file_names)._length));
      }
      for (_ORBIT_tmpvar_7 = 0;
	   _ORBIT_tmpvar_7 < (*target_file_names)._length; _ORBIT_tmpvar_7++) {
	 _ORBIT_tmpvar_9 =
	    strlen((*target_file_names)._buffer[_ORBIT_tmpvar_7]) + 1;
	 giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
					  (_ORBIT_send_buffer), 4);
	 {
	    guchar *_ORBIT_t;

	    _ORBIT_t = alloca(sizeof(_ORBIT_tmpvar_9));
	    memcpy(_ORBIT_t, &(_ORBIT_tmpvar_9), sizeof(_ORBIT_tmpvar_9));
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer), (_ORBIT_t),
					   sizeof(_ORBIT_tmpvar_9));
	 }
	 {
	    guchar *_ORBIT_t;

	    _ORBIT_t =
	       alloca(sizeof
		      ((*target_file_names).
		       _buffer[_ORBIT_tmpvar_7][_ORBIT_tmpvar_8]) *
		      _ORBIT_tmpvar_9);
	       memcpy(_ORBIT_t,
		      ((*target_file_names)._buffer[_ORBIT_tmpvar_7]),
		      sizeof((*target_file_names).
			     _buffer[_ORBIT_tmpvar_7][_ORBIT_tmpvar_8]) *
		      _ORBIT_tmpvar_9);
	    giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER
					   (_ORBIT_send_buffer), (_ORBIT_t),
					   sizeof((*target_file_names).
						  _buffer[_ORBIT_tmpvar_7]
						  [_ORBIT_tmpvar_8]) *
					   _ORBIT_tmpvar_9);
	 }
      }

      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
				       (_ORBIT_send_buffer), 2);
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				     &(options), sizeof(options));
      giop_message_buffer_do_alignment(GIOP_MESSAGE_BUFFER
				       (_ORBIT_send_buffer), 4);
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				     &(error_mode), sizeof(error_mode));
      giop_message_buffer_append_mem(GIOP_MESSAGE_BUFFER(_ORBIT_send_buffer),
				     &(overwrite_mode),
				     sizeof(overwrite_mode));
      giop_send_buffer_write(_ORBIT_send_buffer);
      _ORBIT_completion_status = CORBA_COMPLETED_MAYBE;
      giop_send_buffer_unuse(_ORBIT_send_buffer);
      _ORBIT_send_buffer = NULL;
   }
   {				/* demarshalling */
      register guchar *_ORBIT_curptr;

      _ORBIT_recv_buffer =
	 giop_recv_reply_buffer_use_2(_cnx, _ORBIT_request_id, TRUE);
      if (!_ORBIT_recv_buffer)
	 goto _ORBIT_system_exception;
      _ORBIT_completion_status = CORBA_COMPLETED_YES;
      if (_ORBIT_recv_buffer->message.u.reply.reply_status !=
	  GIOP_NO_EXCEPTION) goto _ORBIT_msg_exception;
      _ORBIT_curptr = GIOP_RECV_BUFFER(_ORBIT_recv_buffer)->cur;
      if (giop_msg_conversion_needed(GIOP_MESSAGE_BUFFER(_ORBIT_recv_buffer))) {
      } else {
      }
      giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      return;
    _ORBIT_system_exception:
      CORBA_exception_set_system(ev, _ORBIT_system_exception_minor,
				 _ORBIT_completion_status);
      giop_recv_buffer_unuse(_ORBIT_recv_buffer);
      giop_send_buffer_unuse(_ORBIT_send_buffer);
      return;
    _ORBIT_msg_exception:
      if (_ORBIT_recv_buffer->message.u.reply.reply_status ==
	  GIOP_LOCATION_FORWARD) {
	 if (_obj->forward_locations != NULL)
	    ORBit_delete_profiles(_obj->forward_locations);
	 _obj->forward_locations = ORBit_demarshal_IOR(_ORBIT_recv_buffer);
	 _cnx = ORBit_object_get_forwarded_connection(_obj);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);

	 goto _ORBIT_retry_request;
      } else {
	 ORBit_handle_exception(_ORBIT_recv_buffer, ev, NULL, _obj->orb);
	 giop_recv_buffer_unuse(_ORBIT_recv_buffer);
	 return;
      }
   }
}
